/*
 * pins_interrupt_vect.h
 *
 * Assigns interrupt vectors to pin names. Do not edit this file:
 * it was automatically generated by pins_interrupt_vect.

 * Published under GNU General Public License, version 3 (GPL-3.0)
 * meta-author Stefan Rueger
 *
 * v 1.0
 * 05.06.2016
 */

#ifndef PINS_INTERRUPT_VECT_H
#define PINS_INTERRUPT_VECT_H

#include "Arduino.h"

// macros for INTx_vect only
#define       INT_vectPin2     INT0_vect
#define       INT_vectPin3     INT1_vect

// macros for PCINTx_vect only
#define     PCINT_vectPin0   PCINT2_vect
#define     PCINT_vectPin1   PCINT2_vect
#define     PCINT_vectPin2   PCINT2_vect
#define     PCINT_vectPin3   PCINT2_vect
#define     PCINT_vectPin4   PCINT2_vect
#define     PCINT_vectPin5   PCINT2_vect
#define     PCINT_vectPin6   PCINT2_vect
#define     PCINT_vectPin7   PCINT2_vect
#define     PCINT_vectPin8   PCINT0_vect
#define     PCINT_vectPin9   PCINT0_vect
#define     PCINT_vectPin10  PCINT0_vect
#define     PCINT_vectPin11  PCINT0_vect
#define     PCINT_vectPin12  PCINT0_vect
#define     PCINT_vectPin13  PCINT0_vect
#define     PCINT_vectPin14  PCINT1_vect
#define     PCINT_vectPin15  PCINT1_vect
#define     PCINT_vectPin16  PCINT1_vect
#define     PCINT_vectPin17  PCINT1_vect
#define     PCINT_vectPin18  PCINT1_vect
#define     PCINT_vectPin19  PCINT1_vect

// macros for either INTx_vect (preferred) or PCINTx_vect
#define INT_PCINT_vectPin0   PCINT2_vect
#define INT_PCINT_vectPin1   PCINT2_vect
#define INT_PCINT_vectPin2     INT0_vect
#define INT_PCINT_vectPin3     INT1_vect
#define INT_PCINT_vectPin4   PCINT2_vect
#define INT_PCINT_vectPin5   PCINT2_vect
#define INT_PCINT_vectPin6   PCINT2_vect
#define INT_PCINT_vectPin7   PCINT2_vect
#define INT_PCINT_vectPin8   PCINT0_vect
#define INT_PCINT_vectPin9   PCINT0_vect
#define INT_PCINT_vectPin10  PCINT0_vect
#define INT_PCINT_vectPin11  PCINT0_vect
#define INT_PCINT_vectPin12  PCINT0_vect
#define INT_PCINT_vectPin13  PCINT0_vect
#define INT_PCINT_vectPin14  PCINT1_vect
#define INT_PCINT_vectPin15  PCINT1_vect
#define INT_PCINT_vectPin16  PCINT1_vect
#define INT_PCINT_vectPin17  PCINT1_vect
#define INT_PCINT_vectPin18  PCINT1_vect
#define INT_PCINT_vectPin19  PCINT1_vect

// macros for either INTx_vect or PCINTx_vect (preferred)
#define PCINT_INT_vectPin0   PCINT2_vect
#define PCINT_INT_vectPin1   PCINT2_vect
#define PCINT_INT_vectPin2   PCINT2_vect
#define PCINT_INT_vectPin3   PCINT2_vect
#define PCINT_INT_vectPin4   PCINT2_vect
#define PCINT_INT_vectPin5   PCINT2_vect
#define PCINT_INT_vectPin6   PCINT2_vect
#define PCINT_INT_vectPin7   PCINT2_vect
#define PCINT_INT_vectPin8   PCINT0_vect
#define PCINT_INT_vectPin9   PCINT0_vect
#define PCINT_INT_vectPin10  PCINT0_vect
#define PCINT_INT_vectPin11  PCINT0_vect
#define PCINT_INT_vectPin12  PCINT0_vect
#define PCINT_INT_vectPin13  PCINT0_vect
#define PCINT_INT_vectPin14  PCINT1_vect
#define PCINT_INT_vectPin15  PCINT1_vect
#define PCINT_INT_vectPin16  PCINT1_vect
#define PCINT_INT_vectPin17  PCINT1_vect
#define PCINT_INT_vectPin18  PCINT1_vect
#define PCINT_INT_vectPin19  PCINT1_vect

// macros to replace static const uint8_t XYZ;
#define	CS	10
#define	COPI	11
#define	CIPO	12
#define	SCK	13
#define	SDA	18
#define	SCL	19
#define	A0	14
#define	A1	15
#define	A2	16
#define	A3	17
#define	A4	18
#define	A5	19
#define	A6	20
#define	A7	21

#endif
