/*
 * pin_mappings.h
 *
 * Assigns Atmel pin numbers to Arduino pin numbers for digisparkpro
 * DO NOT EDIT: it was automatically generated by pins_atmel_map.c

 * Published under GNU General Public License, version 3 (GPL-3.0)
 * meta-author Stefan Rueger
 *
 * v 1.0
 * 12.06.2016
 */

#ifndef PIN_MAPPINGS_H
#define PIN_MAPPING_H

#define ArduinoPin0  AtmelPB0
#define ArduinoPin1  AtmelPB1
#define ArduinoPin2  AtmelPB2
#define ArduinoPin3  AtmelPB3
#define ArduinoPin4  AtmelPB6
#define ArduinoPin5  AtmelPA7
#define ArduinoPin6  AtmelPA0
#define ArduinoPin7  AtmelPA1
#define ArduinoPin8  AtmelPA2
#define ArduinoPin9  AtmelPA3
#define ArduinoPin10 AtmelPA4
#define ArduinoPin11 AtmelPA5
#define ArduinoPin12 AtmelPA6
#define ArduinoPin13 AtmelPB7

#define ArduinoPinA4  ArduinoPin4
#define ArduinoPinA5  ArduinoPin5
#define ArduinoPinA6  ArduinoPin6
#define ArduinoPinA7  ArduinoPin7
#define ArduinoPinA8  ArduinoPin8
#define ArduinoPinA9  ArduinoPin9
#define ArduinoPinA10 ArduinoPin10
#define ArduinoPinA11 ArduinoPin11
#define ArduinoPinA12 ArduinoPin12
#define ArduinoPinA13 ArduinoPin13

#define AtmelCS       ArduinoPin12
#define AtmelCOPI     ArduinoPin10
#define AtmelCIPO     ArduinoPin8
#define AtmelSCK      ArduinoPin11

#define AtmelSDA      ArduinoPin0
#define AtmelSCL      ArduinoPin2

#endif
