/*
 * pins_interrupt_vect.h
 *
 * Assigns interrupt vectors to pin names. Do not edit this file:
 * it was automatically generated by pins_interrupt_vect.

 * Published under GNU General Public License, version 3 (GPL-3.0)
 * meta-author Stefan Rueger
 *
 * v 1.0
 * 05.06.2016
 */

#ifndef PINS_INTERRUPT_VECT_H
#define PINS_INTERRUPT_VECT_H

#include "Arduino.h"

// macros for INTx_vect only
#define       INT_vectPin0     INT2_vect
#define       INT_vectPin1     INT3_vect
#define       INT_vectPin2     INT1_vect
#define       INT_vectPin3     INT0_vect
#define       INT_vectPin7     INT4_vect

// macros to replace static const uint8_t XYZ;
#define	RX	 0
#define	TX	 1
#define	SDA	 2
#define	SCL	 3
#define	CS	17
#define	COPI	16
#define	CIPO	14
#define	SCK	15
#define	A0	18
#define	A1	19
#define	A2	20
#define	A3	21
#define	A4	22
#define	A5	23
#define	A6	24 // D4
#define	A7	25 // D6
#define	A8	26 // D8
#define	A9	27 // D9
#define	A10	28 // D10
#define	A11	29 // D12
#define	KEY	18 // AD0
#define	MUX_IN	24 // ADC8 - A6
#define	MUXA	 6 // D5 - TKD4
#define	MUXB	11 // D11
#define	MUXC	12 // D12 - TKD5
#define	MUXD	13 // D13
#define	BUZZ	 5 // D5
#define	POT	23 // AD5
#define	DC_LCD	10 // D10
#define	LCD_CS	 9 // D9
#define	RST_LCD	 7 // D6
#define	CARD_CS	 8 // D8
#define	TKD0	19 // ADC6 - A1
#define	TKD1	20 // ADC5 - A2
#define	TKD2	21 // ADC4 - A3
#define	TKD3	22 // ADC1 - A4
#define	TKD4	 6 // D5 - MUXA
#define	TKD5	12 // D12 - MUXC
#define	LED1	17 // D17 - RX_Led

#endif
