/*
 * pins_interrupt_vect.h
 *
 * Assigns interrupt vectors to pin names. Do not edit this file:
 * it was automatically generated by pins_interrupt_vect.

 * Published under GNU General Public License, version 3 (GPL-3.0)
 * meta-author Stefan Rueger
 *
 * v 1.0
 * 05.06.2016
 */

#ifndef PINS_INTERRUPT_VECT_H
#define PINS_INTERRUPT_VECT_H

#include "Arduino.h"

// macros for INTx_vect only
#define       INT_vectPin2     INT0_vect

// macros for PCINTx_vect only
#define     PCINT_vectPin0   PCINT0_vect
#define     PCINT_vectPin1   PCINT0_vect
#define     PCINT_vectPin2   PCINT0_vect
#define     PCINT_vectPin3   PCINT0_vect
#define     PCINT_vectPin4   PCINT0_vect
#define     PCINT_vectPin5   PCINT0_vect

// macros for either INTx_vect (preferred) or PCINTx_vect
#define INT_PCINT_vectPin0   PCINT0_vect
#define INT_PCINT_vectPin1   PCINT0_vect
#define INT_PCINT_vectPin2     INT0_vect
#define INT_PCINT_vectPin3   PCINT0_vect
#define INT_PCINT_vectPin4   PCINT0_vect
#define INT_PCINT_vectPin5   PCINT0_vect

// macros for either INTx_vect or PCINTx_vect (preferred)
#define PCINT_INT_vectPin0   PCINT0_vect
#define PCINT_INT_vectPin1   PCINT0_vect
#define PCINT_INT_vectPin2   PCINT0_vect
#define PCINT_INT_vectPin3   PCINT0_vect
#define PCINT_INT_vectPin4   PCINT0_vect
#define PCINT_INT_vectPin5   PCINT0_vect

// macros to replace static const uint8_t XYZ;
#define	CS	 3
#define	PICO	 0
#define	POCI	 1
#define	SCK	 2
#define	SDA	 0
#define	SCL	 2
#define	A0	 6
#define	A1	 7
#define	A2	 8
#define	A3	 9

#endif
