/*
 * pin_mappings.h
 *
 * Assigns Atmel pin numbers to Arduino pin numbers for standard
 * DO NOT EDIT: it was automatically generated by pins_atmel_map.c

 * Published under GNU General Public License, version 3 (GPL-3.0)
 * meta-author Stefan Rueger
 *
 * v 1.0
 * 12.06.2016
 */

#ifndef PIN_MAPPINGS_H
#define PIN_MAPPING_H

#define ArduinoPin0  AtmelPD0
#define ArduinoPin1  AtmelPD1
#define ArduinoPin2  AtmelPD2
#define ArduinoPin3  AtmelPD3
#define ArduinoPin4  AtmelPD4
#define ArduinoPin5  AtmelPD5
#define ArduinoPin6  AtmelPD6
#define ArduinoPin7  AtmelPD7
#define ArduinoPin8  AtmelPB0
#define ArduinoPin9  AtmelPB1
#define ArduinoPin10 AtmelPB2
#define ArduinoPin11 AtmelPB3
#define ArduinoPin12 AtmelPB4
#define ArduinoPin13 AtmelPB5
#define ArduinoPin14 AtmelPC0
#define ArduinoPin15 AtmelPC1
#define ArduinoPin16 AtmelPC2
#define ArduinoPin17 AtmelPC3
#define ArduinoPin18 AtmelPC4
#define ArduinoPin19 AtmelPC5
#define ArduinoPin20 AtmelPC6

#define ArduinoPinA0 ArduinoPin14
#define ArduinoPinA1 ArduinoPin15
#define ArduinoPinA2 ArduinoPin16
#define ArduinoPinA3 ArduinoPin17
#define ArduinoPinA4 ArduinoPin18
#define ArduinoPinA5 ArduinoPin19

#define AtmelCS       ArduinoPin10
#define AtmelCOPI     ArduinoPin11
#define AtmelCIPO     ArduinoPin12
#define AtmelSCK      ArduinoPin13

#define AtmelSDA      ArduinoPin18
#define AtmelSCL      ArduinoPin19

#endif
