#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>

#define PROGMEM

#define digitalPinToPort(P) ( pgm_read_byte( digital_pin_to_port_PGM + (P) ) )
#define digitalPinToBitMask(P) ( pgm_read_byte( digital_pin_to_bit_mask_PGM + (P) ) )
#define digitalPinToTimer(P) ( pgm_read_byte( digital_pin_to_timer_PGM + (P) ) )
#define analogInPinToBit(P) (P)
#define portOutputRegister(P) ( (volatile uint8_t *)( pgm_read_word( port_to_output_PGM + (P))) )
#define portInputRegister(P) ( (volatile uint8_t *)( pgm_read_word( port_to_input_PGM + (P))) )
#define portModeRegister(P) ( (volatile uint8_t *)( pgm_read_word( port_to_mode_PGM + (P))) )

#define NOT_A_PIN 0
#define NOT_A_PORT 0

#define NOT_AN_INTERRUPT -1

// normally _BV(n) is (1<<(n)) BUT here I really need n!
#define _BV(n) (n)

#define PA 1
#define PB 2
#define PC 3
#define PD 4
#define PE 5
#define PF 6
#define PG 7
#define PH 8
#define PJ 10
#define PK 11
#define PL 12

#define NOT_ON_TIMER 0
#define TIMER0A 1
#define TIMER0B 2
#define TIMER1A 3
#define TIMER1B 4
#define TIMER1C 5
#define TIMER2  6
#define TIMER2A 7
#define TIMER2B 8

#define TIMER3A 9
#define TIMER3B 10
#define TIMER3C 11
#define TIMER4A 12
#define TIMER4B 13
#define TIMER4C 14
#define TIMER4D 15
#define TIMER5A 16
#define TIMER5B 17
#define TIMER5C 18

#define ARDUINO_MAIN

unsigned char PCICR, GIMSK, GTCCR;
#define PWM1B 0 // anything to keep copiler from complaining

#include "pins_define.h"


#define PCIE 0

#define defineAx 1

int main() {
  int pin, a2d;

  printf("/*\n"
    " * pin_mappings.h\n"
    " *\n"
    " * Assigns Atmel pin numbers to Arduino pin numbers for %s\n"
    " * DO NOT EDIT: it was automatically generated by pins_atmel_map.c\n\n"
    " * Published under GNU General Public License, version 3 (GPL-3.0)\n"
    " * meta-author Stefan Rueger\n"
    " *\n"
    " * v 1.0\n"
    " * 12.06.2016\n"
    " */\n\n"
    "#ifndef PIN_MAPPINGS_H\n#define PIN_MAPPING_H\n\n", VARIANT
  );

  if(sizeof digital_pin_to_port_PGM != sizeof digital_pin_to_bit_mask_PGM)
    fprintf(stderr, "Houston: digital_pin_to_port_PGM[%d], but digital_pin_to_bit_mask_PGM[%d]?\n",
      (int)sizeof(digital_pin_to_port_PGM), (int)sizeof(digital_pin_to_bit_mask_PGM)), exit(1);

#undef  NUM_DIGITAL_PINS
#define NUM_DIGITAL_PINS (sizeof digital_pin_to_port_PGM)

  for(pin=0; pin < NUM_DIGITAL_PINS; pin++)
    printf("#define ArduinoPin%d%s AtmelP%c%d\n", pin, pin<10 && NUM_DIGITAL_PINS>10? " ": "", 'A'-1+digital_pin_to_port_PGM[pin], digital_pin_to_bit_mask_PGM[pin]);

#if defined(analogInputToDigitalPin) && defined NUM_ANALOG_INPUTS
  printf("\n");
  for(pin=0; pin < NUM_ANALOG_INPUTS+20 /* a few more for odd mappings */; pin++)
    if((a2d=analogInputToDigitalPin(pin)) >=0 && a2d < NUM_DIGITAL_PINS)
      printf("#define ArduinoPinA%d%s ArduinoPin%d\n", pin, pin<10 && NUM_ANALOG_INPUTS>10? " ": "", a2d);
#endif

  printf("\n");
  printf("#ifndef AtmelCS\n");
  printf("#define AtmelCS       ArduinoPin%d\n", CS);
  printf("#endif\n");
  printf("#ifndef AtmelPICO\n");
  printf("#define AtmelPICO     ArduinoPin%d\n", PICO);
  printf("#endif\n");
  printf("#ifndef AtmelPOCI\n");
  printf("#define AtmelPOCI     ArduinoPin%d\n", POCI);
  printf("#endif\n");
  printf("#ifndef AtmelSCK\n");
  printf("#define AtmelSCK      ArduinoPin%d\n", SCK);
  printf("#endif\n");
  printf("\n");
  printf("#ifndef AtmelSDA\n");
  printf("#define AtmelSDA      ArduinoPin%d\n", SDA);
  printf("#endif\n");
  printf("#ifndef AtmelSCL\n");
  printf("#define AtmelSCL      ArduinoPin%d\n", SCL);
  printf("#endif\n");

  printf("\n#endif\n");
}
