/*
 * pin_mappings.h
 *
 * Assigns Atmel pin numbers to Arduino pin numbers for MoteinoMEGA
 * DO NOT EDIT: it was automatically generated by pins_atmel_map.c

 * Published under GNU General Public License, version 3 (GPL-3.0)
 * meta-author Stefan Rueger
 *
 * v 1.0
 * 12.06.2016
 */

#ifndef PIN_MAPPINGS_H
#define PIN_MAPPING_H

#define ArduinoPin0  AtmelPB0
#define ArduinoPin1  AtmelPB1
#define ArduinoPin2  AtmelPB2
#define ArduinoPin3  AtmelPB3
#define ArduinoPin4  AtmelPB4
#define ArduinoPin5  AtmelPB5
#define ArduinoPin6  AtmelPB6
#define ArduinoPin7  AtmelPB7
#define ArduinoPin8  AtmelPD0
#define ArduinoPin9  AtmelPD1
#define ArduinoPin10 AtmelPD2
#define ArduinoPin11 AtmelPD3
#define ArduinoPin12 AtmelPD4
#define ArduinoPin13 AtmelPD5
#define ArduinoPin14 AtmelPD6
#define ArduinoPin15 AtmelPD7
#define ArduinoPin16 AtmelPC0
#define ArduinoPin17 AtmelPC1
#define ArduinoPin18 AtmelPC2
#define ArduinoPin19 AtmelPC3
#define ArduinoPin20 AtmelPC4
#define ArduinoPin21 AtmelPC5
#define ArduinoPin22 AtmelPC6
#define ArduinoPin23 AtmelPC7
#define ArduinoPin24 AtmelPA0
#define ArduinoPin25 AtmelPA1
#define ArduinoPin26 AtmelPA2
#define ArduinoPin27 AtmelPA3
#define ArduinoPin28 AtmelPA4
#define ArduinoPin29 AtmelPA5
#define ArduinoPin30 AtmelPA6
#define ArduinoPin31 AtmelPA7

#define ArduinoPinA0 ArduinoPin24
#define ArduinoPinA1 ArduinoPin25
#define ArduinoPinA2 ArduinoPin26
#define ArduinoPinA3 ArduinoPin27
#define ArduinoPinA4 ArduinoPin28
#define ArduinoPinA5 ArduinoPin29
#define ArduinoPinA6 ArduinoPin30
#define ArduinoPinA7 ArduinoPin31

#ifndef AtmelCS
#define AtmelCS       ArduinoPin4
#endif
#ifndef AtmelPICO
#define AtmelPICO     ArduinoPin5
#endif
#ifndef AtmelPOCI
#define AtmelPOCI     ArduinoPin6
#endif
#ifndef AtmelSCK
#define AtmelSCK      ArduinoPin7
#endif

#ifndef AtmelSDA
#define AtmelSDA      ArduinoPin17
#endif
#ifndef AtmelSCL
#define AtmelSCL      ArduinoPin16
#endif

#endif
