/*
 * pin_mappings.h
 *
 * Assigns Atmel pin numbers to Arduino pin numbers for digispark
 * DO NOT EDIT: it was automatically generated by pins_atmel_map.c

 * Published under GNU General Public License, version 3 (GPL-3.0)
 * meta-author Stefan Rueger
 *
 * v 1.0
 * 12.06.2016
 */

#ifndef PIN_MAPPINGS_H
#define PIN_MAPPING_H

#define ArduinoPin0 AtmelPB0
#define ArduinoPin1 AtmelPB1
#define ArduinoPin2 AtmelPB2
#define ArduinoPin3 AtmelPB3
#define ArduinoPin4 AtmelPB4
#define ArduinoPin5 AtmelPB5

#define ArduinoPinA0 ArduinoPin5
#define ArduinoPinA1 ArduinoPin2
#define ArduinoPinA2 ArduinoPin4
#define ArduinoPinA3 ArduinoPin3

#ifndef AtmelCS
#define AtmelCS       ArduinoPin3
#endif
#ifndef AtmelPICO
#define AtmelPICO     ArduinoPin0
#endif
#ifndef AtmelPOCI
#define AtmelPOCI     ArduinoPin1
#endif
#ifndef AtmelSCK
#define AtmelSCK      ArduinoPin2
#endif

#ifndef AtmelSDA
#define AtmelSDA      ArduinoPin0
#endif
#ifndef AtmelSCL
#define AtmelSCL      ArduinoPin2
#endif

#endif
