/*
 * pins_interrupt_vect.h
 *
 * Assigns interrupt vectors to pin names. Do not edit this file:
 * it was automatically generated by pins_interrupt_vect.

 * Published under GNU General Public License, version 3 (GPL-3.0)
 * meta-author Stefan Rueger
 *
 * v 1.0
 * 05.06.2016
 */

#ifndef PINS_INTERRUPT_VECT_H
#define PINS_INTERRUPT_VECT_H

#include "Arduino.h"

// macros for INTx_vect only
#define       INT_vectPin0     INT2_vect
#define       INT_vectPin1     INT3_vect
#define       INT_vectPin2     INT1_vect
#define       INT_vectPin3     INT0_vect
#define       INT_vectPin7     INT4_vect

// macros to replace static const uint8_t XYZ;
#define	RX	 0
#define	TX	 1
#define	SDA	 2
#define	SCL	 3
#define	CS	17
#define	COPI	16
#define	CIPO	14
#define	SCK	15
#define	A0	18
#define	A1	19
#define	A2	20
#define	A3	21
#define	A4	22
#define	A5	23
#define	A6	24 // D4
#define	A7	25 // D6
#define	A8	26 // D8
#define	A9	27 // D9
#define	A10	28 // D10
#define	A11	29 // D12
#define	MUX_IN	20 // A2
#define	MUXA	 7 // D7
#define	MUXB	 8 // D8
#define	MUXC	11 // D11
#define	MUXI	13 // D13
#define	TRIM	21 // A3
#define	SENSE_A	22 // A4
#define	SENSE_B	23 // A5
#define	IN_A1	 6 // D6 - A7
#define	IN_A2	 5 // D5
#define	IN_B1	10 // D10
#define	IN_B2	 9 // D9
#define	TK1	18 // A0
#define	TK2	19 // A1
#define	TK3	 4 // A6
#define	TK4	12 // A11

#endif
