/*
 * pin_mappings.h
 *
 * Assigns Atmel pin numbers to Arduino pin numbers for mega
 * DO NOT EDIT: it was automatically generated by pins_atmel_map.c

 * Published under GNU General Public License, version 3 (GPL-3.0)
 * meta-author Stefan Rueger
 *
 * v 1.0
 * 12.06.2016
 */

#ifndef PIN_MAPPINGS_H
#define PIN_MAPPING_H

#define ArduinoPin0  AtmelPE0
#define ArduinoPin1  AtmelPE1
#define ArduinoPin2  AtmelPE4
#define ArduinoPin3  AtmelPE5
#define ArduinoPin4  AtmelPG5
#define ArduinoPin5  AtmelPE3
#define ArduinoPin6  AtmelPH3
#define ArduinoPin7  AtmelPH4
#define ArduinoPin8  AtmelPH5
#define ArduinoPin9  AtmelPH6
#define ArduinoPin10 AtmelPB4
#define ArduinoPin11 AtmelPB5
#define ArduinoPin12 AtmelPB6
#define ArduinoPin13 AtmelPB7
#define ArduinoPin14 AtmelPJ1
#define ArduinoPin15 AtmelPJ0
#define ArduinoPin16 AtmelPH1
#define ArduinoPin17 AtmelPH0
#define ArduinoPin18 AtmelPD3
#define ArduinoPin19 AtmelPD2
#define ArduinoPin20 AtmelPD1
#define ArduinoPin21 AtmelPD0
#define ArduinoPin22 AtmelPA0
#define ArduinoPin23 AtmelPA1
#define ArduinoPin24 AtmelPA2
#define ArduinoPin25 AtmelPA3
#define ArduinoPin26 AtmelPA4
#define ArduinoPin27 AtmelPA5
#define ArduinoPin28 AtmelPA6
#define ArduinoPin29 AtmelPA7
#define ArduinoPin30 AtmelPC7
#define ArduinoPin31 AtmelPC6
#define ArduinoPin32 AtmelPC5
#define ArduinoPin33 AtmelPC4
#define ArduinoPin34 AtmelPC3
#define ArduinoPin35 AtmelPC2
#define ArduinoPin36 AtmelPC1
#define ArduinoPin37 AtmelPC0
#define ArduinoPin38 AtmelPD7
#define ArduinoPin39 AtmelPG2
#define ArduinoPin40 AtmelPG1
#define ArduinoPin41 AtmelPG0
#define ArduinoPin42 AtmelPL7
#define ArduinoPin43 AtmelPL6
#define ArduinoPin44 AtmelPL5
#define ArduinoPin45 AtmelPL4
#define ArduinoPin46 AtmelPL3
#define ArduinoPin47 AtmelPL2
#define ArduinoPin48 AtmelPL1
#define ArduinoPin49 AtmelPL0
#define ArduinoPin50 AtmelPB3
#define ArduinoPin51 AtmelPB2
#define ArduinoPin52 AtmelPB1
#define ArduinoPin53 AtmelPB0
#define ArduinoPin54 AtmelPF0
#define ArduinoPin55 AtmelPF1
#define ArduinoPin56 AtmelPF2
#define ArduinoPin57 AtmelPF3
#define ArduinoPin58 AtmelPF4
#define ArduinoPin59 AtmelPF5
#define ArduinoPin60 AtmelPF6
#define ArduinoPin61 AtmelPF7
#define ArduinoPin62 AtmelPK0
#define ArduinoPin63 AtmelPK1
#define ArduinoPin64 AtmelPK2
#define ArduinoPin65 AtmelPK3
#define ArduinoPin66 AtmelPK4
#define ArduinoPin67 AtmelPK5
#define ArduinoPin68 AtmelPK6
#define ArduinoPin69 AtmelPK7

#define ArduinoPinA0  ArduinoPin54
#define ArduinoPinA1  ArduinoPin55
#define ArduinoPinA2  ArduinoPin56
#define ArduinoPinA3  ArduinoPin57
#define ArduinoPinA4  ArduinoPin58
#define ArduinoPinA5  ArduinoPin59
#define ArduinoPinA6  ArduinoPin60
#define ArduinoPinA7  ArduinoPin61
#define ArduinoPinA8  ArduinoPin62
#define ArduinoPinA9  ArduinoPin63
#define ArduinoPinA10 ArduinoPin64
#define ArduinoPinA11 ArduinoPin65
#define ArduinoPinA12 ArduinoPin66
#define ArduinoPinA13 ArduinoPin67
#define ArduinoPinA14 ArduinoPin68
#define ArduinoPinA15 ArduinoPin69

#ifndef AtmelCS
#define AtmelCS       ArduinoPin53
#endif
#ifndef AtmelPICO
#define AtmelPICO     ArduinoPin51
#endif
#ifndef AtmelPOCI
#define AtmelPOCI     ArduinoPin50
#endif
#ifndef AtmelSCK
#define AtmelSCK      ArduinoPin52
#endif

#ifndef AtmelSDA
#define AtmelSDA      ArduinoPin20
#endif
#ifndef AtmelSCL
#define AtmelSCL      ArduinoPin21
#endif

#endif
