/*
 * pins_interrupt_vect.h
 *
 * Assigns interrupt vectors to pin names. Do not edit this file:
 * it was automatically generated by pins_interrupt_vect.

 * Published under GNU General Public License, version 3 (GPL-3.0)
 * meta-author Stefan Rueger
 *
 * v 1.0
 * 05.06.2016
 */

#ifndef PINS_INTERRUPT_VECT_H
#define PINS_INTERRUPT_VECT_H

#include "Arduino.h"

// macros for INTx_vect only
#define       INT_vectPin2     INT0_vect
#define       INT_vectPin3     INT1_vect
#define       INT_vectPin18    INT5_vect
#define       INT_vectPin19    INT4_vect
#define       INT_vectPin20    INT3_vect
#define       INT_vectPin21    INT2_vect

// macros for PCINTx_vect only
#define     PCINT_vectPin0   PCINT1_vect
#define     PCINT_vectPin10  PCINT0_vect
#define     PCINT_vectPin11  PCINT0_vect
#define     PCINT_vectPin12  PCINT0_vect
#define     PCINT_vectPin13  PCINT0_vect
#define     PCINT_vectPin14  PCINT1_vect
#define     PCINT_vectPin15  PCINT1_vect
#define     PCINT_vectPin50  PCINT0_vect
#define     PCINT_vectPin51  PCINT0_vect
#define     PCINT_vectPin52  PCINT0_vect
#define     PCINT_vectPin53  PCINT0_vect
#define     PCINT_vectPin62  PCINT2_vect
#define     PCINT_vectPin63  PCINT2_vect
#define     PCINT_vectPin64  PCINT2_vect
#define     PCINT_vectPin65  PCINT2_vect
#define     PCINT_vectPin66  PCINT2_vect
#define     PCINT_vectPin67  PCINT2_vect
#define     PCINT_vectPin68  PCINT2_vect
#define     PCINT_vectPin69  PCINT2_vect

// macros for either INTx_vect (preferred) or PCINTx_vect
#define INT_PCINT_vectPin0   PCINT1_vect
#define INT_PCINT_vectPin2     INT0_vect
#define INT_PCINT_vectPin3     INT1_vect
#define INT_PCINT_vectPin10  PCINT0_vect
#define INT_PCINT_vectPin11  PCINT0_vect
#define INT_PCINT_vectPin12  PCINT0_vect
#define INT_PCINT_vectPin13  PCINT0_vect
#define INT_PCINT_vectPin14  PCINT1_vect
#define INT_PCINT_vectPin15  PCINT1_vect
#define INT_PCINT_vectPin18    INT5_vect
#define INT_PCINT_vectPin19    INT4_vect
#define INT_PCINT_vectPin20    INT3_vect
#define INT_PCINT_vectPin21    INT2_vect
#define INT_PCINT_vectPin50  PCINT0_vect
#define INT_PCINT_vectPin51  PCINT0_vect
#define INT_PCINT_vectPin52  PCINT0_vect
#define INT_PCINT_vectPin53  PCINT0_vect
#define INT_PCINT_vectPin62  PCINT2_vect
#define INT_PCINT_vectPin63  PCINT2_vect
#define INT_PCINT_vectPin64  PCINT2_vect
#define INT_PCINT_vectPin65  PCINT2_vect
#define INT_PCINT_vectPin66  PCINT2_vect
#define INT_PCINT_vectPin67  PCINT2_vect
#define INT_PCINT_vectPin68  PCINT2_vect
#define INT_PCINT_vectPin69  PCINT2_vect

// macros for either INTx_vect or PCINTx_vect (preferred)
#define PCINT_INT_vectPin0   PCINT1_vect
#define PCINT_INT_vectPin2     INT0_vect
#define PCINT_INT_vectPin3     INT1_vect
#define PCINT_INT_vectPin10  PCINT0_vect
#define PCINT_INT_vectPin11  PCINT0_vect
#define PCINT_INT_vectPin12  PCINT0_vect
#define PCINT_INT_vectPin13  PCINT0_vect
#define PCINT_INT_vectPin14  PCINT1_vect
#define PCINT_INT_vectPin15  PCINT1_vect
#define PCINT_INT_vectPin18    INT5_vect
#define PCINT_INT_vectPin19    INT4_vect
#define PCINT_INT_vectPin20    INT3_vect
#define PCINT_INT_vectPin21    INT2_vect
#define PCINT_INT_vectPin50  PCINT0_vect
#define PCINT_INT_vectPin51  PCINT0_vect
#define PCINT_INT_vectPin52  PCINT0_vect
#define PCINT_INT_vectPin53  PCINT0_vect
#define PCINT_INT_vectPin62  PCINT2_vect
#define PCINT_INT_vectPin63  PCINT2_vect
#define PCINT_INT_vectPin64  PCINT2_vect
#define PCINT_INT_vectPin65  PCINT2_vect
#define PCINT_INT_vectPin66  PCINT2_vect
#define PCINT_INT_vectPin67  PCINT2_vect
#define PCINT_INT_vectPin68  PCINT2_vect
#define PCINT_INT_vectPin69  PCINT2_vect

// macros to replace static const uint8_t XYZ;
#define	CS	53
#define	PICO	51
#define	POCI	50
#define	SCK	52
#define	SDA	20
#define	SCL	21
#define	A0	54
#define	A1	55
#define	A2	56
#define	A3	57
#define	A4	58
#define	A5	59
#define	A6	60
#define	A7	61
#define	A8	62
#define	A9	63
#define	A10	64
#define	A11	65
#define	A12	66
#define	A13	67
#define	A14	68
#define	A15	69

#endif
