/*
 * pins_interrupt_vect.h
 *
 * Assigns interrupt vectors to pin names. Do not edit this file:
 * it was automatically generated by pins_interrupt_vect.

 * Published under GNU General Public License, version 3 (GPL-3.0)
 * meta-author Stefan Rueger
 *
 * v 1.0
 * 05.06.2016
 */

#ifndef PINS_INTERRUPT_VECT_H
#define PINS_INTERRUPT_VECT_H

#include "Arduino.h"

// macros for INTx_vect only
#define       INT_vectPin8     INT0_vect

// macros for PCINTx_vect only
#define     PCINT_vectPin0   PCINT0_vect
#define     PCINT_vectPin1   PCINT0_vect
#define     PCINT_vectPin2   PCINT0_vect
#define     PCINT_vectPin3   PCINT0_vect
#define     PCINT_vectPin4   PCINT0_vect
#define     PCINT_vectPin5   PCINT0_vect
#define     PCINT_vectPin6   PCINT0_vect
#define     PCINT_vectPin7   PCINT0_vect
#define     PCINT_vectPin8   PCINT1_vect
#define     PCINT_vectPin9   PCINT1_vect
#define     PCINT_vectPin10  PCINT1_vect
#define     PCINT_vectPin11  PCINT1_vect

// macros for either INTx_vect (preferred) or PCINTx_vect
#define INT_PCINT_vectPin0   PCINT0_vect
#define INT_PCINT_vectPin1   PCINT0_vect
#define INT_PCINT_vectPin2   PCINT0_vect
#define INT_PCINT_vectPin3   PCINT0_vect
#define INT_PCINT_vectPin4   PCINT0_vect
#define INT_PCINT_vectPin5   PCINT0_vect
#define INT_PCINT_vectPin6   PCINT0_vect
#define INT_PCINT_vectPin7   PCINT0_vect
#define INT_PCINT_vectPin8     INT0_vect
#define INT_PCINT_vectPin9   PCINT1_vect
#define INT_PCINT_vectPin10  PCINT1_vect
#define INT_PCINT_vectPin11  PCINT1_vect

// macros for either INTx_vect or PCINTx_vect (preferred)
#define PCINT_INT_vectPin0   PCINT0_vect
#define PCINT_INT_vectPin1   PCINT0_vect
#define PCINT_INT_vectPin2   PCINT0_vect
#define PCINT_INT_vectPin3   PCINT0_vect
#define PCINT_INT_vectPin4   PCINT0_vect
#define PCINT_INT_vectPin5   PCINT0_vect
#define PCINT_INT_vectPin6   PCINT0_vect
#define PCINT_INT_vectPin7   PCINT0_vect
#define PCINT_INT_vectPin8   PCINT1_vect
#define PCINT_INT_vectPin9   PCINT1_vect
#define PCINT_INT_vectPin10  PCINT1_vect
#define PCINT_INT_vectPin11  PCINT1_vect

// macros to replace static const uint8_t XYZ;
#define	CS	 7
#define	PICO	 6
#define	POCI	 5
#define	SCK	 4
#define	SDA	 6
#define	SCL	 4
#define	A0	 0
#define	A1	 1
#define	A2	 2
#define	A3	 3
#define	A4	 4
#define	A5	 5
#define	A6	 6
#define	A7	 7

#endif
