/*
 * pin_mappings.h
 *
 * Assigns Atmel pin numbers to Arduino pin numbers for attiny84
 * DO NOT EDIT: it was automatically generated by pins_atmel_map.c

 * Published under GNU General Public License, version 3 (GPL-3.0)
 * meta-author Stefan Rueger
 *
 * v 1.0
 * 12.06.2016
 */

#ifndef PIN_MAPPINGS_H
#define PIN_MAPPING_H

#define ArduinoPin0  AtmelPA0
#define ArduinoPin1  AtmelPA1
#define ArduinoPin2  AtmelPA2
#define ArduinoPin3  AtmelPA3
#define ArduinoPin4  AtmelPA4
#define ArduinoPin5  AtmelPA5
#define ArduinoPin6  AtmelPA6
#define ArduinoPin7  AtmelPA7
#define ArduinoPin8  AtmelPB2
#define ArduinoPin9  AtmelPB1
#define ArduinoPin10 AtmelPB0
#define ArduinoPin11 AtmelPB3

#define ArduinoPinA0 ArduinoPin0
#define ArduinoPinA1 ArduinoPin1
#define ArduinoPinA2 ArduinoPin2
#define ArduinoPinA3 ArduinoPin3
#define ArduinoPinA4 ArduinoPin4
#define ArduinoPinA5 ArduinoPin5
#define ArduinoPinA6 ArduinoPin6
#define ArduinoPinA7 ArduinoPin7

#define AtmelCS       ArduinoPin7
#define AtmelCOPI     ArduinoPin6
#define AtmelCIPO     ArduinoPin5
#define AtmelSCK      ArduinoPin4

#define AtmelSDA      ArduinoPin6
#define AtmelSCL      ArduinoPin4

#endif
