/*
 * atmel_ports.h
 *
 * DO NOT EDIT - was generated by mk_atmel_ports.pl
 * Header file to manipulate Atmel ports.
 *
 * Published under GNU General Public License, version 3 (GPL-3.0)
 * meta-author Stefan Rueger
 *
 * First version 12.06.2016
 * Generated 03.03.2023
 *
 * Usage
 *
 * #define activityLedPin AtmelPB5
 * // or #define activityLedPin ArduinoPin13
 *
 * // make LED pin output
 * UR_DDR(activityLedPin)  |= UR_BV(activityLedPin);
 * // switch LED on
 * UR_PORT(activityLedPin) |= UR_BV(activityLedPin);
 * // switch LED off
 * UR_PORT(activityLedPin) &= ~UR_BV(activityLedPin);
 * // toggle LED
 * UR_PIN(activityLedPin)  |= UR_BV(activityLedPin);
 * UR_PORT(activityLedPin) ^= UR_BV(activityLedPin); // Older AVRs (ATmega8 etc)
 *
 * // check whether pins are the same
 * #if UR_PIN_VALUE(AtmelSCK) == UR_PIN_VALUE(activityLedPin)
 * #warning cannot use LED independently from SPI - please resolder LED
 * #endif
 *
 * Published under GNU General Public License, version 3 (GPL-3.0)
 * meta-author Stefan Rueger
 *
 * v 1.0
 * 12.06.2016
 */

#ifndef ATMEL_PORTS_H
#define ATMEL_PORTS_H

#undef A
#undef B
#undef C
#undef D
#undef E
#undef F
#undef G
#undef H
#undef I
#undef J
#undef K
#undef L

#define UR_PORT_VALUE_A (0<<3)
#define UR_PORT_VALUE_B (1<<3)
#define UR_PORT_VALUE_C (2<<3)
#define UR_PORT_VALUE_D (3<<3)
#define UR_PORT_VALUE_E (4<<3)
#define UR_PORT_VALUE_F (5<<3)
#define UR_PORT_VALUE_G (6<<3)
#define UR_PORT_VALUE_H (7<<3)
#define UR_PORT_VALUE_I (8<<3)
#define UR_PORT_VALUE_J (9<<3)
#define UR_PORT_VALUE_K (10<<3)
#define UR_PORT_VALUE_L (11<<3)

#undef PORT
#undef PIN
#undef DDR

#define ur_arg_chr(name, chr, bit) name##chr   // sth like PORTA, PINC, UR_PORT_VALUE_B
#define ur_arg_bit(name, chr, bit)       bit   // bit number
#define ur_arg(name, what, a, b) (ur_arg_##what(name, a, b))

#define UR_PORT(pin) (ur_arg(PORT, chr, pin))   // PORTA, PORTB, ...
#define UR_DDR(pin)  (ur_arg(DDR,  chr, pin))   // DDRA, DDRB, ...
#define UR_PIN(pin)  (ur_arg(PIN,  chr, pin))   // PINA, PINB, ...
#define UR_BIT(pin)  (ur_arg(*, bit, pin))      // 0, 1, ..., 7
#define UR_BV(pin)   (1<<(ur_arg(*, bit, pin))) // 1, 2, ..., 128

// numeric value of an Atmel pin and a port - useful for #if comparisons
#define UR_PIN_VALUE(pin) ((ur_arg(UR_PORT_VALUE_, chr, pin))+(ur_arg(*, bit, pin)))
#define UR_PORT_VALUE(pin) (ur_arg(UR_PORT_VALUE_, chr, pin))

#define AtmelPA0 A,0
#define AtmelPA1 A,1
#define AtmelPA2 A,2
#define AtmelPA3 A,3
#define AtmelPA4 A,4
#define AtmelPA5 A,5
#define AtmelPA6 A,6
#define AtmelPA7 A,7

#define AtmelPB0 B,0
#define AtmelPB1 B,1
#define AtmelPB2 B,2
#define AtmelPB3 B,3
#define AtmelPB4 B,4
#define AtmelPB5 B,5
#define AtmelPB6 B,6
#define AtmelPB7 B,7

#define AtmelPC0 C,0
#define AtmelPC1 C,1
#define AtmelPC2 C,2
#define AtmelPC3 C,3
#define AtmelPC4 C,4
#define AtmelPC5 C,5
#define AtmelPC6 C,6
#define AtmelPC7 C,7

#define AtmelPD0 D,0
#define AtmelPD1 D,1
#define AtmelPD2 D,2
#define AtmelPD3 D,3
#define AtmelPD4 D,4
#define AtmelPD5 D,5
#define AtmelPD6 D,6
#define AtmelPD7 D,7

#define AtmelPE0 E,0
#define AtmelPE1 E,1
#define AtmelPE2 E,2
#define AtmelPE3 E,3
#define AtmelPE4 E,4
#define AtmelPE5 E,5
#define AtmelPE6 E,6
#define AtmelPE7 E,7

#define AtmelPF0 F,0
#define AtmelPF1 F,1
#define AtmelPF2 F,2
#define AtmelPF3 F,3
#define AtmelPF4 F,4
#define AtmelPF5 F,5
#define AtmelPF6 F,6
#define AtmelPF7 F,7

#define AtmelPG0 G,0
#define AtmelPG1 G,1
#define AtmelPG2 G,2
#define AtmelPG3 G,3
#define AtmelPG4 G,4
#define AtmelPG5 G,5
#define AtmelPG6 G,6
#define AtmelPG7 G,7

#define AtmelPH0 H,0
#define AtmelPH1 H,1
#define AtmelPH2 H,2
#define AtmelPH3 H,3
#define AtmelPH4 H,4
#define AtmelPH5 H,5
#define AtmelPH6 H,6
#define AtmelPH7 H,7

#define AtmelPI0 I,0
#define AtmelPI1 I,1
#define AtmelPI2 I,2
#define AtmelPI3 I,3
#define AtmelPI4 I,4
#define AtmelPI5 I,5
#define AtmelPI6 I,6
#define AtmelPI7 I,7

#define AtmelPJ0 J,0
#define AtmelPJ1 J,1
#define AtmelPJ2 J,2
#define AtmelPJ3 J,3
#define AtmelPJ4 J,4
#define AtmelPJ5 J,5
#define AtmelPJ6 J,6
#define AtmelPJ7 J,7

#define AtmelPK0 K,0
#define AtmelPK1 K,1
#define AtmelPK2 K,2
#define AtmelPK3 K,3
#define AtmelPK4 K,4
#define AtmelPK5 K,5
#define AtmelPK6 K,6
#define AtmelPK7 K,7

#define AtmelPL0 L,0
#define AtmelPL1 L,1
#define AtmelPL2 L,2
#define AtmelPL3 L,3
#define AtmelPL4 L,4
#define AtmelPL5 L,5
#define AtmelPL6 L,6
#define AtmelPL7 L,7


#if defined(__AVR_ATmega328__) || defined(__AVR_ATmega328P__) || defined(__AVR_ATmega168A__) || defined(__AVR_ATmega168PA__) || defined(__AVR_ATmega168__) || defined(__AVR_ATmega168P__) || defined(__AVR_ATmega88A__) || defined(__AVR_ATmega88PA__) || defined(__AVR_ATmega88__) || defined(__AVR_ATmega88P__) || defined(__AVR_ATmega48A__) || defined(__AVR_ATmega48PA__) || defined(__AVR_ATmega48__) || defined(__AVR_ATmega48P__) || defined(__AVR_ATmega8__)

#define ArduinoPin0  AtmelPD0
#define ArduinoPin1  AtmelPD1
#define ArduinoPin2  AtmelPD2
#define ArduinoPin3  AtmelPD3
#define ArduinoPin4  AtmelPD4
#define ArduinoPin5  AtmelPD5
#define ArduinoPin6  AtmelPD6
#define ArduinoPin7  AtmelPD7
#define ArduinoPin8  AtmelPB0
#define ArduinoPin9  AtmelPB1
#define ArduinoPin10 AtmelPB2
#define ArduinoPin11 AtmelPB3
#define ArduinoPin12 AtmelPB4
#define ArduinoPin13 AtmelPB5
#define ArduinoPin14 AtmelPC0
#define ArduinoPin15 AtmelPC1
#define ArduinoPin16 AtmelPC2
#define ArduinoPin17 AtmelPC3
#define ArduinoPin18 AtmelPC4
#define ArduinoPin19 AtmelPC5
#define ArduinoPin20 AtmelPC6

#define ArduinoPinA0 ArduinoPin14
#define ArduinoPinA1 ArduinoPin15
#define ArduinoPinA2 ArduinoPin16
#define ArduinoPinA3 ArduinoPin17
#define ArduinoPinA4 ArduinoPin18
#define ArduinoPinA5 ArduinoPin19

#define AtmelCS       ArduinoPin10
#define AtmelCOPI     ArduinoPin11
#define AtmelCIPO     ArduinoPin12
#define AtmelSCK      ArduinoPin13

#define AtmelSDA      ArduinoPin18
#define AtmelSCL      ArduinoPin19

#elif defined(__AVR_ATmega1284__) || defined(__AVR_ATmega1284P__) || defined(__AVR_ATmega644A__) || defined(__AVR_ATmega644PA__) || defined(__AVR_ATmega644__) || defined(__AVR_ATmega644P__) || defined(__AVR_ATmega324A__) || defined(__AVR_ATmega324PA__) || defined(__AVR_ATmega164A__) || defined(__AVR_ATmega164PA__) || defined(__AVR_ATmega16__) || defined(__AVR_ATmega32__)

#define ArduinoPin0  AtmelPB0
#define ArduinoPin1  AtmelPB1
#define ArduinoPin2  AtmelPB2
#define ArduinoPin3  AtmelPB3
#define ArduinoPin4  AtmelPB4
#define ArduinoPin5  AtmelPB5
#define ArduinoPin6  AtmelPB6
#define ArduinoPin7  AtmelPB7
#define ArduinoPin8  AtmelPD0
#define ArduinoPin9  AtmelPD1
#define ArduinoPin10 AtmelPD2
#define ArduinoPin11 AtmelPD3
#define ArduinoPin12 AtmelPD4
#define ArduinoPin13 AtmelPD5
#define ArduinoPin14 AtmelPD6
#define ArduinoPin15 AtmelPD7
#define ArduinoPin16 AtmelPC0
#define ArduinoPin17 AtmelPC1
#define ArduinoPin18 AtmelPC2
#define ArduinoPin19 AtmelPC3
#define ArduinoPin20 AtmelPC4
#define ArduinoPin21 AtmelPC5
#define ArduinoPin22 AtmelPC6
#define ArduinoPin23 AtmelPC7
#define ArduinoPin24 AtmelPA0
#define ArduinoPin25 AtmelPA1
#define ArduinoPin26 AtmelPA2
#define ArduinoPin27 AtmelPA3
#define ArduinoPin28 AtmelPA4
#define ArduinoPin29 AtmelPA5
#define ArduinoPin30 AtmelPA6
#define ArduinoPin31 AtmelPA7

#define ArduinoPinA0 ArduinoPin24
#define ArduinoPinA1 ArduinoPin25
#define ArduinoPinA2 ArduinoPin26
#define ArduinoPinA3 ArduinoPin27
#define ArduinoPinA4 ArduinoPin28
#define ArduinoPinA5 ArduinoPin29
#define ArduinoPinA6 ArduinoPin30
#define ArduinoPinA7 ArduinoPin31

#define AtmelCS       ArduinoPin4
#define AtmelCOPI     ArduinoPin5
#define AtmelCIPO     ArduinoPin6
#define AtmelSCK      ArduinoPin7

#define AtmelSDA      ArduinoPin17
#define AtmelSCL      ArduinoPin16

#elif defined(__AVR_ATmega2560__) || defined(__AVR_ATmega2561__) || defined(__AVR_ATmega1280__) || defined(__AVR_ATmega1281__) || defined(__AVR_ATmega640__)

#define ArduinoPin0  AtmelPE0
#define ArduinoPin1  AtmelPE1
#define ArduinoPin2  AtmelPE4
#define ArduinoPin3  AtmelPE5
#define ArduinoPin4  AtmelPG5
#define ArduinoPin5  AtmelPE3
#define ArduinoPin6  AtmelPH3
#define ArduinoPin7  AtmelPH4
#define ArduinoPin8  AtmelPH5
#define ArduinoPin9  AtmelPH6
#define ArduinoPin10 AtmelPB4
#define ArduinoPin11 AtmelPB5
#define ArduinoPin12 AtmelPB6
#define ArduinoPin13 AtmelPB7
#define ArduinoPin14 AtmelPJ1
#define ArduinoPin15 AtmelPJ0
#define ArduinoPin16 AtmelPH1
#define ArduinoPin17 AtmelPH0
#define ArduinoPin18 AtmelPD3
#define ArduinoPin19 AtmelPD2
#define ArduinoPin20 AtmelPD1
#define ArduinoPin21 AtmelPD0
#define ArduinoPin22 AtmelPA0
#define ArduinoPin23 AtmelPA1
#define ArduinoPin24 AtmelPA2
#define ArduinoPin25 AtmelPA3
#define ArduinoPin26 AtmelPA4
#define ArduinoPin27 AtmelPA5
#define ArduinoPin28 AtmelPA6
#define ArduinoPin29 AtmelPA7
#define ArduinoPin30 AtmelPC7
#define ArduinoPin31 AtmelPC6
#define ArduinoPin32 AtmelPC5
#define ArduinoPin33 AtmelPC4
#define ArduinoPin34 AtmelPC3
#define ArduinoPin35 AtmelPC2
#define ArduinoPin36 AtmelPC1
#define ArduinoPin37 AtmelPC0
#define ArduinoPin38 AtmelPD7
#define ArduinoPin39 AtmelPG2
#define ArduinoPin40 AtmelPG1
#define ArduinoPin41 AtmelPG0
#define ArduinoPin42 AtmelPL7
#define ArduinoPin43 AtmelPL6
#define ArduinoPin44 AtmelPL5
#define ArduinoPin45 AtmelPL4
#define ArduinoPin46 AtmelPL3
#define ArduinoPin47 AtmelPL2
#define ArduinoPin48 AtmelPL1
#define ArduinoPin49 AtmelPL0
#define ArduinoPin50 AtmelPB3
#define ArduinoPin51 AtmelPB2
#define ArduinoPin52 AtmelPB1
#define ArduinoPin53 AtmelPB0
#define ArduinoPin54 AtmelPF0
#define ArduinoPin55 AtmelPF1
#define ArduinoPin56 AtmelPF2
#define ArduinoPin57 AtmelPF3
#define ArduinoPin58 AtmelPF4
#define ArduinoPin59 AtmelPF5
#define ArduinoPin60 AtmelPF6
#define ArduinoPin61 AtmelPF7
#define ArduinoPin62 AtmelPK0
#define ArduinoPin63 AtmelPK1
#define ArduinoPin64 AtmelPK2
#define ArduinoPin65 AtmelPK3
#define ArduinoPin66 AtmelPK4
#define ArduinoPin67 AtmelPK5
#define ArduinoPin68 AtmelPK6
#define ArduinoPin69 AtmelPK7

#define ArduinoPinA0  ArduinoPin54
#define ArduinoPinA1  ArduinoPin55
#define ArduinoPinA2  ArduinoPin56
#define ArduinoPinA3  ArduinoPin57
#define ArduinoPinA4  ArduinoPin58
#define ArduinoPinA5  ArduinoPin59
#define ArduinoPinA6  ArduinoPin60
#define ArduinoPinA7  ArduinoPin61
#define ArduinoPinA8  ArduinoPin62
#define ArduinoPinA9  ArduinoPin63
#define ArduinoPinA10 ArduinoPin64
#define ArduinoPinA11 ArduinoPin65
#define ArduinoPinA12 ArduinoPin66
#define ArduinoPinA13 ArduinoPin67
#define ArduinoPinA14 ArduinoPin68
#define ArduinoPinA15 ArduinoPin69

#define AtmelCS       ArduinoPin53
#define AtmelCOPI     ArduinoPin51
#define AtmelCIPO     ArduinoPin50
#define AtmelSCK      ArduinoPin52

#define AtmelSDA      ArduinoPin20
#define AtmelSCL      ArduinoPin21

#elif defined(__AVR_ATtiny24__) || defined(__AVR_ATtiny44__) || defined(__AVR_ATtiny84__)

#define ArduinoPin0  AtmelPA0
#define ArduinoPin1  AtmelPA1
#define ArduinoPin2  AtmelPA2
#define ArduinoPin3  AtmelPA3
#define ArduinoPin4  AtmelPA4
#define ArduinoPin5  AtmelPA5
#define ArduinoPin6  AtmelPA6
#define ArduinoPin7  AtmelPA7
#define ArduinoPin8  AtmelPB2
#define ArduinoPin9  AtmelPB1
#define ArduinoPin10 AtmelPB0
#define ArduinoPin11 AtmelPB3

#define ArduinoPinA0 ArduinoPin0
#define ArduinoPinA1 ArduinoPin1
#define ArduinoPinA2 ArduinoPin2
#define ArduinoPinA3 ArduinoPin3
#define ArduinoPinA4 ArduinoPin4
#define ArduinoPinA5 ArduinoPin5
#define ArduinoPinA6 ArduinoPin6
#define ArduinoPinA7 ArduinoPin7

#define AtmelCS       ArduinoPin7
#define AtmelCOPI     ArduinoPin6
#define AtmelCIPO     ArduinoPin5
#define AtmelSCK      ArduinoPin4

#define AtmelSDA      ArduinoPin6
#define AtmelSCL      ArduinoPin4

#elif defined(__AVR_ATtiny25__) || defined(__AVR_ATtiny45__) || defined(__AVR_ATtiny85__)

#define ArduinoPin0 AtmelPB0
#define ArduinoPin1 AtmelPB1
#define ArduinoPin2 AtmelPB2
#define ArduinoPin3 AtmelPB3
#define ArduinoPin4 AtmelPB4
#define ArduinoPin5 AtmelPB5

#define ArduinoPinA0 ArduinoPin5
#define ArduinoPinA1 ArduinoPin2
#define ArduinoPinA2 ArduinoPin4
#define ArduinoPinA3 ArduinoPin3

#define AtmelCS       ArduinoPin3
#define AtmelCOPI     ArduinoPin0
#define AtmelCIPO     ArduinoPin1
#define AtmelSCK      ArduinoPin2

#define AtmelSDA      ArduinoPin0
#define AtmelSCL      ArduinoPin2

#elif defined(__AVR_ATtiny87__) || defined(__AVR_ATtiny167__)

#define ArduinoPin0  AtmelPB0
#define ArduinoPin1  AtmelPB1
#define ArduinoPin2  AtmelPB2
#define ArduinoPin3  AtmelPB3
#define ArduinoPin4  AtmelPB6
#define ArduinoPin5  AtmelPA7
#define ArduinoPin6  AtmelPA0
#define ArduinoPin7  AtmelPA1
#define ArduinoPin8  AtmelPA2
#define ArduinoPin9  AtmelPA3
#define ArduinoPin10 AtmelPA4
#define ArduinoPin11 AtmelPA5
#define ArduinoPin12 AtmelPA6
#define ArduinoPin13 AtmelPB7

#define ArduinoPinA4  ArduinoPin4
#define ArduinoPinA5  ArduinoPin5
#define ArduinoPinA6  ArduinoPin6
#define ArduinoPinA7  ArduinoPin7
#define ArduinoPinA8  ArduinoPin8
#define ArduinoPinA9  ArduinoPin9
#define ArduinoPinA10 ArduinoPin10
#define ArduinoPinA11 ArduinoPin11
#define ArduinoPinA12 ArduinoPin12
#define ArduinoPinA13 ArduinoPin13

#define AtmelCS       ArduinoPin12
#define AtmelCOPI     ArduinoPin10
#define AtmelCIPO     ArduinoPin8
#define AtmelSCK      ArduinoPin11

#define AtmelSDA      ArduinoPin0
#define AtmelSCL      ArduinoPin2

#else
// Will not know mapping of ArduinoPinX to AtmelPXX: don't allow their use
#pragma GCC poison ArduinoPinA0 ArduinoPinA1 ArduinoPinA2 ArduinoPinA3 ArduinoPinA4 ArduinoPinA5 ArduinoPinA6
#pragma GCC poison ArduinoPinA7 ArduinoPinA8 ArduinoPinA9 ArduinoPinA10 ArduinoPinA11 ArduinoPinA12 ArduinoPinA13
#pragma GCC poison ArduinoPinA14 ArduinoPinA15 ArduinoPin0 ArduinoPin1 ArduinoPin2 ArduinoPin3 ArduinoPin4 ArduinoPin5
#pragma GCC poison ArduinoPin6 ArduinoPin7 ArduinoPin8 ArduinoPin9 ArduinoPin10 ArduinoPin11 ArduinoPin12 ArduinoPin13
#pragma GCC poison ArduinoPin14 ArduinoPin15 ArduinoPin16 ArduinoPin17 ArduinoPin18 ArduinoPin19 ArduinoPin20
#pragma GCC poison ArduinoPin21 ArduinoPin22 ArduinoPin23 ArduinoPin24 ArduinoPin25 ArduinoPin26 ArduinoPin27
#pragma GCC poison ArduinoPin28 ArduinoPin29 ArduinoPin30 ArduinoPin31 ArduinoPin32 ArduinoPin33 ArduinoPin34
#pragma GCC poison ArduinoPin35 ArduinoPin36 ArduinoPin37 ArduinoPin38 ArduinoPin39 ArduinoPin40 ArduinoPin41
#pragma GCC poison ArduinoPin42 ArduinoPin43 ArduinoPin44 ArduinoPin45 ArduinoPin46 ArduinoPin47 ArduinoPin48
#pragma GCC poison ArduinoPin49 ArduinoPin50 ArduinoPin51 ArduinoPin52 ArduinoPin53 ArduinoPin54 ArduinoPin55
#pragma GCC poison ArduinoPin56 ArduinoPin57 ArduinoPin58 ArduinoPin59 ArduinoPin60 ArduinoPin61 ArduinoPin62
#pragma GCC poison ArduinoPin63 ArduinoPin64 ArduinoPin65 ArduinoPin66 ArduinoPin67 ArduinoPin68 ArduinoPin69
#endif

#endif
