/*
 * Do not edit: automatically generated by mkavrintel.pl
 *
 * urboot_devicename.h
 *
 * Device name from libavrdude-avrintel.h
 *
 * Published under GNU General Public License, version 3 (GPL-3.0)
 * Meta-author Stefan Rueger <stefan.rueger@urclocks.com>
 *
 * v 1.18
 * 02.06.2024
 *
 */

#ifndef URBOOT_DEVICENAME_H
#define URBOOT_DEVICENAME_H

#undef __AVR_DEVICE_NAME__

#if 0
#elif defined(__AVR_ATtiny4__)
#define __AVR_DEVICE_NAME__ attiny4

#elif defined(__AVR_ATtiny5__)
#define __AVR_DEVICE_NAME__ attiny5

#elif defined(__AVR_ATtiny9__)
#define __AVR_DEVICE_NAME__ attiny9

#elif defined(__AVR_ATtiny10__)
#define __AVR_DEVICE_NAME__ attiny10

#elif defined(__AVR_ATtiny20__)
#define __AVR_DEVICE_NAME__ attiny20

#elif defined(__AVR_ATtiny40__)
#define __AVR_DEVICE_NAME__ attiny40

#elif defined(__AVR_ATtiny102__)
#define __AVR_DEVICE_NAME__ attiny102

#elif defined(__AVR_ATtiny104__)
#define __AVR_DEVICE_NAME__ attiny104

#elif defined(__AVR_ATtiny11__)
#define __AVR_DEVICE_NAME__ attiny11

#elif defined(__AVR_ATtiny12__)
#define __AVR_DEVICE_NAME__ attiny12

#elif defined(__AVR_ATtiny13__)
#define __AVR_DEVICE_NAME__ attiny13

#elif defined(__AVR_ATtiny13A__)
#define __AVR_DEVICE_NAME__ attiny13a

#elif defined(__AVR_ATtiny15__)
#define __AVR_DEVICE_NAME__ attiny15

#elif defined(__AVR_ATtiny22__)
#define __AVR_DEVICE_NAME__ attiny22

#elif defined(__AVR_ATtiny24__)
#define __AVR_DEVICE_NAME__ attiny24

#elif defined(__AVR_ATtiny24A__)
#define __AVR_DEVICE_NAME__ attiny24a

#elif defined(__AVR_ATtiny25__)
#define __AVR_DEVICE_NAME__ attiny25

#elif defined(__AVR_ATtiny26__)
#define __AVR_DEVICE_NAME__ attiny26

#elif defined(__AVR_ATtiny28__)
#define __AVR_DEVICE_NAME__ attiny28

#elif defined(__AVR_ATtiny43U__)
#define __AVR_DEVICE_NAME__ attiny43u

#elif defined(__AVR_ATtiny44__)
#define __AVR_DEVICE_NAME__ attiny44

#elif defined(__AVR_ATtiny44A__)
#define __AVR_DEVICE_NAME__ attiny44a

#elif defined(__AVR_ATtiny45__)
#define __AVR_DEVICE_NAME__ attiny45

#elif defined(__AVR_ATtiny48__)
#define __AVR_DEVICE_NAME__ attiny48

#elif defined(__AVR_ATtiny84__)
#define __AVR_DEVICE_NAME__ attiny84

#elif defined(__AVR_ATtiny84A__)
#define __AVR_DEVICE_NAME__ attiny84a

#elif defined(__AVR_ATtiny85__)
#define __AVR_DEVICE_NAME__ attiny85

#elif defined(__AVR_ATtiny87__)
#define __AVR_DEVICE_NAME__ attiny87

#elif defined(__AVR_ATtiny88__)
#define __AVR_DEVICE_NAME__ attiny88

#elif defined(__AVR_ATtiny167__)
#define __AVR_DEVICE_NAME__ attiny167

#elif defined(__AVR_ATtiny261__)
#define __AVR_DEVICE_NAME__ attiny261

#elif defined(__AVR_ATtiny261A__)
#define __AVR_DEVICE_NAME__ attiny261a

#elif defined(__AVR_ATtiny441__)
#define __AVR_DEVICE_NAME__ attiny441

#elif defined(__AVR_ATtiny461__)
#define __AVR_DEVICE_NAME__ attiny461

#elif defined(__AVR_ATtiny461A__)
#define __AVR_DEVICE_NAME__ attiny461a

#elif defined(__AVR_ATtiny828__)
#define __AVR_DEVICE_NAME__ attiny828

#elif defined(__AVR_ATtiny828R__)
#define __AVR_DEVICE_NAME__ attiny828r

#elif defined(__AVR_ATtiny841__)
#define __AVR_DEVICE_NAME__ attiny841

#elif defined(__AVR_ATtiny861__)
#define __AVR_DEVICE_NAME__ attiny861

#elif defined(__AVR_ATtiny861A__)
#define __AVR_DEVICE_NAME__ attiny861a

#elif defined(__AVR_ATtiny1634__)
#define __AVR_DEVICE_NAME__ attiny1634

#elif defined(__AVR_ATtiny1634R__)
#define __AVR_DEVICE_NAME__ attiny1634r

#elif defined(__AVR_ATtiny2313__)
#define __AVR_DEVICE_NAME__ attiny2313

#elif defined(__AVR_ATtiny2313A__)
#define __AVR_DEVICE_NAME__ attiny2313a

#elif defined(__AVR_ATtiny4313__)
#define __AVR_DEVICE_NAME__ attiny4313

#elif defined(__AVR_ATmega8__)
#define __AVR_DEVICE_NAME__ atmega8

#elif defined(__AVR_ATmega8A__)
#define __AVR_DEVICE_NAME__ atmega8a

#elif defined(__AVR_ATmega8HVA__)
#define __AVR_DEVICE_NAME__ atmega8hva

#elif defined(__AVR_ATmega8U2__)
#define __AVR_DEVICE_NAME__ atmega8u2

#elif defined(__AVR_ATmega16__)
#define __AVR_DEVICE_NAME__ atmega16

#elif defined(__AVR_ATmega16A__)
#define __AVR_DEVICE_NAME__ atmega16a

#elif defined(__AVR_ATmega16HVA__)
#define __AVR_DEVICE_NAME__ atmega16hva

#elif defined(__AVR_ATmega16HVB__)
#define __AVR_DEVICE_NAME__ atmega16hvb

#elif defined(__AVR_ATmega16HVBrevB__) || defined(__AVR_ATmega16HVBREVB__)
#define __AVR_DEVICE_NAME__ atmega16hvbrevb

#elif defined(__AVR_ATmega16M1__)
#define __AVR_DEVICE_NAME__ atmega16m1

#elif defined(__AVR_ATmega16HVA2__)
#define __AVR_DEVICE_NAME__ atmega16hva2

#elif defined(__AVR_ATmega16U2__)
#define __AVR_DEVICE_NAME__ atmega16u2

#elif defined(__AVR_ATmega16U4__)
#define __AVR_DEVICE_NAME__ atmega16u4

#elif defined(__AVR_ATmega32__)
#define __AVR_DEVICE_NAME__ atmega32

#elif defined(__AVR_ATmega32A__)
#define __AVR_DEVICE_NAME__ atmega32a

#elif defined(__AVR_ATmega32HVB__)
#define __AVR_DEVICE_NAME__ atmega32hvb

#elif defined(__AVR_ATmega32HVBrevB__) || defined(__AVR_ATmega32HVBREVB__)
#define __AVR_DEVICE_NAME__ atmega32hvbrevb

#elif defined(__AVR_ATmega32C1__)
#define __AVR_DEVICE_NAME__ atmega32c1

#elif defined(__AVR_ATmega32M1__)
#define __AVR_DEVICE_NAME__ atmega32m1

#elif defined(__AVR_ATmega32HVE2__)
#define __AVR_DEVICE_NAME__ atmega32hve2

#elif defined(__AVR_ATmega32U2__)
#define __AVR_DEVICE_NAME__ atmega32u2

#elif defined(__AVR_ATmega32U4__)
#define __AVR_DEVICE_NAME__ atmega32u4

#elif defined(__AVR_ATmega32U6__)
#define __AVR_DEVICE_NAME__ atmega32u6

#elif defined(__AVR_ATmega48__)
#define __AVR_DEVICE_NAME__ atmega48

#elif defined(__AVR_ATmega48A__)
#define __AVR_DEVICE_NAME__ atmega48a

#elif defined(__AVR_ATmega48P__)
#define __AVR_DEVICE_NAME__ atmega48p

#elif defined(__AVR_ATmega48PA__)
#define __AVR_DEVICE_NAME__ atmega48pa

#elif defined(__AVR_ATmega48PB__)
#define __AVR_DEVICE_NAME__ atmega48pb

#elif defined(__AVR_ATmega64__)
#define __AVR_DEVICE_NAME__ atmega64

#elif defined(__AVR_ATmega64A__)
#define __AVR_DEVICE_NAME__ atmega64a

#elif defined(__AVR_ATmega64HVE__)
#define __AVR_DEVICE_NAME__ atmega64hve

#elif defined(__AVR_ATmega64C1__)
#define __AVR_DEVICE_NAME__ atmega64c1

#elif defined(__AVR_ATmega64M1__)
#define __AVR_DEVICE_NAME__ atmega64m1

#elif defined(__AVR_ATmega64HVE2__)
#define __AVR_DEVICE_NAME__ atmega64hve2

#elif defined(__AVR_ATmega64RFR2__)
#define __AVR_DEVICE_NAME__ atmega64rfr2

#elif defined(__AVR_ATmega88__)
#define __AVR_DEVICE_NAME__ atmega88

#elif defined(__AVR_ATmega88A__)
#define __AVR_DEVICE_NAME__ atmega88a

#elif defined(__AVR_ATmega88P__)
#define __AVR_DEVICE_NAME__ atmega88p

#elif defined(__AVR_ATmega88PA__)
#define __AVR_DEVICE_NAME__ atmega88pa

#elif defined(__AVR_ATmega88PB__)
#define __AVR_DEVICE_NAME__ atmega88pb

#elif defined(__AVR_ATmega103__)
#define __AVR_DEVICE_NAME__ atmega103

#elif defined(__AVR_ATmega103comp__)
#define __AVR_DEVICE_NAME__ atmega103comp

#elif defined(__AVR_ATmega128__)
#define __AVR_DEVICE_NAME__ atmega128

#elif defined(__AVR_ATmega128A__)
#define __AVR_DEVICE_NAME__ atmega128a

#elif defined(__AVR_ATmega128RFA1__)
#define __AVR_DEVICE_NAME__ atmega128rfa1

#elif defined(__AVR_ATmega128RFR2__)
#define __AVR_DEVICE_NAME__ atmega128rfr2

#elif defined(__AVR_ATmega161__)
#define __AVR_DEVICE_NAME__ atmega161

#elif defined(__AVR_ATmega161comp__)
#define __AVR_DEVICE_NAME__ atmega161comp

#elif defined(__AVR_ATmega162__)
#define __AVR_DEVICE_NAME__ atmega162

#elif defined(__AVR_ATmega163__)
#define __AVR_DEVICE_NAME__ atmega163

#elif defined(__AVR_ATmega164A__)
#define __AVR_DEVICE_NAME__ atmega164a

#elif defined(__AVR_ATmega164P__)
#define __AVR_DEVICE_NAME__ atmega164p

#elif defined(__AVR_ATmega164PA__)
#define __AVR_DEVICE_NAME__ atmega164pa

#elif defined(__AVR_ATmega165__)
#define __AVR_DEVICE_NAME__ atmega165

#elif defined(__AVR_ATmega165A__)
#define __AVR_DEVICE_NAME__ atmega165a

#elif defined(__AVR_ATmega165P__)
#define __AVR_DEVICE_NAME__ atmega165p

#elif defined(__AVR_ATmega165PA__)
#define __AVR_DEVICE_NAME__ atmega165pa

#elif defined(__AVR_ATmega168__)
#define __AVR_DEVICE_NAME__ atmega168

#elif defined(__AVR_ATmega168A__)
#define __AVR_DEVICE_NAME__ atmega168a

#elif defined(__AVR_ATmega168P__)
#define __AVR_DEVICE_NAME__ atmega168p

#elif defined(__AVR_ATmega168PA__)
#define __AVR_DEVICE_NAME__ atmega168pa

#elif defined(__AVR_ATmega168PB__)
#define __AVR_DEVICE_NAME__ atmega168pb

#elif defined(__AVR_ATmega169__)
#define __AVR_DEVICE_NAME__ atmega169

#elif defined(__AVR_ATmega169A__)
#define __AVR_DEVICE_NAME__ atmega169a

#elif defined(__AVR_ATmega169P__)
#define __AVR_DEVICE_NAME__ atmega169p

#elif defined(__AVR_ATmega169PA__)
#define __AVR_DEVICE_NAME__ atmega169pa

#elif defined(__AVR_ATmega256RFR2__)
#define __AVR_DEVICE_NAME__ atmega256rfr2

#elif defined(__AVR_ATmega323__)
#define __AVR_DEVICE_NAME__ atmega323

#elif defined(__AVR_ATmega324A__)
#define __AVR_DEVICE_NAME__ atmega324a

#elif defined(__AVR_ATmega324P__)
#define __AVR_DEVICE_NAME__ atmega324p

#elif defined(__AVR_ATmega324PA__)
#define __AVR_DEVICE_NAME__ atmega324pa

#elif defined(__AVR_ATmega324PB__)
#define __AVR_DEVICE_NAME__ atmega324pb

#elif defined(__AVR_ATmega325__)
#define __AVR_DEVICE_NAME__ atmega325

#elif defined(__AVR_ATmega325A__)
#define __AVR_DEVICE_NAME__ atmega325a

#elif defined(__AVR_ATmega325P__)
#define __AVR_DEVICE_NAME__ atmega325p

#elif defined(__AVR_ATmega325PA__)
#define __AVR_DEVICE_NAME__ atmega325pa

#elif defined(__AVR_ATmega328__)
#define __AVR_DEVICE_NAME__ atmega328

#elif defined(__AVR_ATmega328P__)
#define __AVR_DEVICE_NAME__ atmega328p

#elif defined(__AVR_ATmega328PB__)
#define __AVR_DEVICE_NAME__ atmega328pb

#elif defined(__AVR_ATmega329__)
#define __AVR_DEVICE_NAME__ atmega329

#elif defined(__AVR_ATmega329A__)
#define __AVR_DEVICE_NAME__ atmega329a

#elif defined(__AVR_ATmega329P__)
#define __AVR_DEVICE_NAME__ atmega329p

#elif defined(__AVR_ATmega329PA__)
#define __AVR_DEVICE_NAME__ atmega329pa

#elif defined(__AVR_ATmega406__)
#define __AVR_DEVICE_NAME__ atmega406

#elif defined(__AVR_ATmega640__)
#define __AVR_DEVICE_NAME__ atmega640

#elif defined(__AVR_ATmega644__)
#define __AVR_DEVICE_NAME__ atmega644

#elif defined(__AVR_ATmega644A__)
#define __AVR_DEVICE_NAME__ atmega644a

#elif defined(__AVR_ATmega644P__)
#define __AVR_DEVICE_NAME__ atmega644p

#elif defined(__AVR_ATmega644PA__)
#define __AVR_DEVICE_NAME__ atmega644pa

#elif defined(__AVR_ATmega644RFR2__)
#define __AVR_DEVICE_NAME__ atmega644rfr2

#elif defined(__AVR_ATmega645__)
#define __AVR_DEVICE_NAME__ atmega645

#elif defined(__AVR_ATmega645A__)
#define __AVR_DEVICE_NAME__ atmega645a

#elif defined(__AVR_ATmega645P__)
#define __AVR_DEVICE_NAME__ atmega645p

#elif defined(__AVR_ATmega649__)
#define __AVR_DEVICE_NAME__ atmega649

#elif defined(__AVR_ATmega649A__)
#define __AVR_DEVICE_NAME__ atmega649a

#elif defined(__AVR_ATmega649P__)
#define __AVR_DEVICE_NAME__ atmega649p

#elif defined(__AVR_ATmega1280__)
#define __AVR_DEVICE_NAME__ atmega1280

#elif defined(__AVR_ATmega1281__)
#define __AVR_DEVICE_NAME__ atmega1281

#elif defined(__AVR_ATmega1284__)
#define __AVR_DEVICE_NAME__ atmega1284

#elif defined(__AVR_ATmega1284P__)
#define __AVR_DEVICE_NAME__ atmega1284p

#elif defined(__AVR_ATmega1284RFR2__)
#define __AVR_DEVICE_NAME__ atmega1284rfr2

#elif defined(__AVR_ATmega2560__)
#define __AVR_DEVICE_NAME__ atmega2560

#elif defined(__AVR_ATmega2561__)
#define __AVR_DEVICE_NAME__ atmega2561

#elif defined(__AVR_ATmega2564RFR2__)
#define __AVR_DEVICE_NAME__ atmega2564rfr2

#elif defined(__AVR_ATmega3250__)
#define __AVR_DEVICE_NAME__ atmega3250

#elif defined(__AVR_ATmega3250A__)
#define __AVR_DEVICE_NAME__ atmega3250a

#elif defined(__AVR_ATmega3250P__)
#define __AVR_DEVICE_NAME__ atmega3250p

#elif defined(__AVR_ATmega3250PA__)
#define __AVR_DEVICE_NAME__ atmega3250pa

#elif defined(__AVR_ATmega3290__)
#define __AVR_DEVICE_NAME__ atmega3290

#elif defined(__AVR_ATmega3290A__)
#define __AVR_DEVICE_NAME__ atmega3290a

#elif defined(__AVR_ATmega3290P__)
#define __AVR_DEVICE_NAME__ atmega3290p

#elif defined(__AVR_ATmega3290PA__)
#define __AVR_DEVICE_NAME__ atmega3290pa

#elif defined(__AVR_ATmega6450__)
#define __AVR_DEVICE_NAME__ atmega6450

#elif defined(__AVR_ATmega6450A__)
#define __AVR_DEVICE_NAME__ atmega6450a

#elif defined(__AVR_ATmega6450P__)
#define __AVR_DEVICE_NAME__ atmega6450p

#elif defined(__AVR_ATmega6490__)
#define __AVR_DEVICE_NAME__ atmega6490

#elif defined(__AVR_ATmega6490A__)
#define __AVR_DEVICE_NAME__ atmega6490a

#elif defined(__AVR_ATmega6490P__)
#define __AVR_DEVICE_NAME__ atmega6490p

#elif defined(__AVR_ATmega8515__)
#define __AVR_DEVICE_NAME__ atmega8515

#elif defined(__AVR_ATmega8535__)
#define __AVR_DEVICE_NAME__ atmega8535

#elif defined(__AVR_AT43USB320__)
#define __AVR_DEVICE_NAME__ at43usb320

#elif defined(__AVR_AT43USB355__)
#define __AVR_DEVICE_NAME__ at43usb355

#elif defined(__AVR_AT76C711__)
#define __AVR_DEVICE_NAME__ at76c711

#elif defined(__AVR_AT86RF401__)
#define __AVR_DEVICE_NAME__ at86rf401

#elif defined(__AVR_AT89S51__)
#define __AVR_DEVICE_NAME__ at89s51

#elif defined(__AVR_AT89S52__)
#define __AVR_DEVICE_NAME__ at89s52

#elif defined(__AVR_AT90PWM1__)
#define __AVR_DEVICE_NAME__ at90pwm1

#elif defined(__AVR_AT90PWM2__)
#define __AVR_DEVICE_NAME__ at90pwm2

#elif defined(__AVR_AT90PWM2B__)
#define __AVR_DEVICE_NAME__ at90pwm2b

#elif defined(__AVR_AT90PWM3__)
#define __AVR_DEVICE_NAME__ at90pwm3

#elif defined(__AVR_AT90PWM3B__)
#define __AVR_DEVICE_NAME__ at90pwm3b

#elif defined(__AVR_AT90CAN32__)
#define __AVR_DEVICE_NAME__ at90can32

#elif defined(__AVR_AT90CAN64__)
#define __AVR_DEVICE_NAME__ at90can64

#elif defined(__AVR_AT90PWM81__)
#define __AVR_DEVICE_NAME__ at90pwm81

#elif defined(__AVR_AT90USB82__)
#define __AVR_DEVICE_NAME__ at90usb82

#elif defined(__AVR_AT90SCR100__)
#define __AVR_DEVICE_NAME__ at90scr100

#elif defined(__AVR_AT90SCR100H__)
#define __AVR_DEVICE_NAME__ at90scr100h

#elif defined(__AVR_AT90CAN128__)
#define __AVR_DEVICE_NAME__ at90can128

#elif defined(__AVR_AT90PWM161__)
#define __AVR_DEVICE_NAME__ at90pwm161

#elif defined(__AVR_AT90USB162__)
#define __AVR_DEVICE_NAME__ at90usb162

#elif defined(__AVR_AT90PWM216__)
#define __AVR_DEVICE_NAME__ at90pwm216

#elif defined(__AVR_AT90PWM316__)
#define __AVR_DEVICE_NAME__ at90pwm316

#elif defined(__AVR_AT90USB646__)
#define __AVR_DEVICE_NAME__ at90usb646

#elif defined(__AVR_AT90USB647__)
#define __AVR_DEVICE_NAME__ at90usb647

#elif defined(__AVR_AT90S1200__)
#define __AVR_DEVICE_NAME__ at90s1200

#elif defined(__AVR_AT90USB1286__)
#define __AVR_DEVICE_NAME__ at90usb1286

#elif defined(__AVR_AT90USB1287__)
#define __AVR_DEVICE_NAME__ at90usb1287

#elif defined(__AVR_AT90S2313__)
#define __AVR_DEVICE_NAME__ at90s2313

#elif defined(__AVR_AT90S2323__)
#define __AVR_DEVICE_NAME__ at90s2323

#elif defined(__AVR_AT90S2333__)
#define __AVR_DEVICE_NAME__ at90s2333

#elif defined(__AVR_AT90S2343__)
#define __AVR_DEVICE_NAME__ at90s2343

#elif defined(__AVR_AT90S4414__)
#define __AVR_DEVICE_NAME__ at90s4414

#elif defined(__AVR_AT90S4433__)
#define __AVR_DEVICE_NAME__ at90s4433

#elif defined(__AVR_AT90S4434__)
#define __AVR_DEVICE_NAME__ at90s4434

#elif defined(__AVR_AT90S8515__)
#define __AVR_DEVICE_NAME__ at90s8515

#elif defined(__AVR_AT90S8515comp__)
#define __AVR_DEVICE_NAME__ at90s8515comp

#elif defined(__AVR_AT90C8534__)
#define __AVR_DEVICE_NAME__ at90c8534

#elif defined(__AVR_AT90S8535__)
#define __AVR_DEVICE_NAME__ at90s8535

#elif defined(__AVR_AT90S8535comp__)
#define __AVR_DEVICE_NAME__ at90s8535comp

#elif defined(__AVR_AT94K__)
#define __AVR_DEVICE_NAME__ at94k

#elif defined(__AVR_ATA5272__)
#define __AVR_DEVICE_NAME__ ata5272

#elif defined(__AVR_ATA5505__)
#define __AVR_DEVICE_NAME__ ata5505

#elif defined(__AVR_ATA5700M322__)
#define __AVR_DEVICE_NAME__ ata5700m322

#elif defined(__AVR_ATA5702M322__)
#define __AVR_DEVICE_NAME__ ata5702m322

#elif defined(__AVR_ATA5781__)
#define __AVR_DEVICE_NAME__ ata5781

#elif defined(__AVR_ATA5782__)
#define __AVR_DEVICE_NAME__ ata5782

#elif defined(__AVR_ATA5783__)
#define __AVR_DEVICE_NAME__ ata5783

#elif defined(__AVR_ATA5787__)
#define __AVR_DEVICE_NAME__ ata5787

#elif defined(__AVR_ATA5790__)
#define __AVR_DEVICE_NAME__ ata5790

#elif defined(__AVR_ATA5790N__)
#define __AVR_DEVICE_NAME__ ata5790n

#elif defined(__AVR_ATA5791__)
#define __AVR_DEVICE_NAME__ ata5791

#elif defined(__AVR_ATA5795__)
#define __AVR_DEVICE_NAME__ ata5795

#elif defined(__AVR_ATA5831__)
#define __AVR_DEVICE_NAME__ ata5831

#elif defined(__AVR_ATA5832__)
#define __AVR_DEVICE_NAME__ ata5832

#elif defined(__AVR_ATA5833__)
#define __AVR_DEVICE_NAME__ ata5833

#elif defined(__AVR_ATA5835__)
#define __AVR_DEVICE_NAME__ ata5835

#elif defined(__AVR_ATA6285__)
#define __AVR_DEVICE_NAME__ ata6285

#elif defined(__AVR_ATA6286__)
#define __AVR_DEVICE_NAME__ ata6286

#elif defined(__AVR_ATA6289__)
#define __AVR_DEVICE_NAME__ ata6289

#elif defined(__AVR_ATA6612C__)
#define __AVR_DEVICE_NAME__ ata6612c

#elif defined(__AVR_ATA6613C__)
#define __AVR_DEVICE_NAME__ ata6613c

#elif defined(__AVR_ATA6614Q__)
#define __AVR_DEVICE_NAME__ ata6614q

#elif defined(__AVR_ATA6616C__)
#define __AVR_DEVICE_NAME__ ata6616c

#elif defined(__AVR_ATA6617C__)
#define __AVR_DEVICE_NAME__ ata6617c

#elif defined(__AVR_ATA8210__)
#define __AVR_DEVICE_NAME__ ata8210

#elif defined(__AVR_ATA8215__)
#define __AVR_DEVICE_NAME__ ata8215

#elif defined(__AVR_ATA8510__)
#define __AVR_DEVICE_NAME__ ata8510

#elif defined(__AVR_ATA8515__)
#define __AVR_DEVICE_NAME__ ata8515

#elif defined(__AVR_ATA664251__)
#define __AVR_DEVICE_NAME__ ata664251

#elif defined(__AVR_M3000__)
#define __AVR_DEVICE_NAME__ m3000

#elif defined(__AVR_LGT8F88P__)
#define __AVR_DEVICE_NAME__ lgt8f88p

#elif defined(__AVR_LGT8F168P__)
#define __AVR_DEVICE_NAME__ lgt8f168p

#elif defined(__AVR_LGT8F328P__)
#define __AVR_DEVICE_NAME__ lgt8f328p

#elif defined(__AVR_ATxmega8E5__)
#define __AVR_DEVICE_NAME__ atxmega8e5

#elif defined(__AVR_ATxmega16A4__)
#define __AVR_DEVICE_NAME__ atxmega16a4

#elif defined(__AVR_ATxmega16A4U__)
#define __AVR_DEVICE_NAME__ atxmega16a4u

#elif defined(__AVR_ATxmega16C4__)
#define __AVR_DEVICE_NAME__ atxmega16c4

#elif defined(__AVR_ATxmega16D4__)
#define __AVR_DEVICE_NAME__ atxmega16d4

#elif defined(__AVR_ATxmega16E5__)
#define __AVR_DEVICE_NAME__ atxmega16e5

#elif defined(__AVR_ATxmega32C3__)
#define __AVR_DEVICE_NAME__ atxmega32c3

#elif defined(__AVR_ATxmega32D3__)
#define __AVR_DEVICE_NAME__ atxmega32d3

#elif defined(__AVR_ATxmega32A4__)
#define __AVR_DEVICE_NAME__ atxmega32a4

#elif defined(__AVR_ATxmega32A4U__)
#define __AVR_DEVICE_NAME__ atxmega32a4u

#elif defined(__AVR_ATxmega32C4__)
#define __AVR_DEVICE_NAME__ atxmega32c4

#elif defined(__AVR_ATxmega32D4__)
#define __AVR_DEVICE_NAME__ atxmega32d4

#elif defined(__AVR_ATxmega32E5__)
#define __AVR_DEVICE_NAME__ atxmega32e5

#elif defined(__AVR_ATxmega64A1__)
#define __AVR_DEVICE_NAME__ atxmega64a1

#elif defined(__AVR_ATxmega64A1U__)
#define __AVR_DEVICE_NAME__ atxmega64a1u

#elif defined(__AVR_ATxmega64B1__)
#define __AVR_DEVICE_NAME__ atxmega64b1

#elif defined(__AVR_ATxmega64A3__)
#define __AVR_DEVICE_NAME__ atxmega64a3

#elif defined(__AVR_ATxmega64A3U__)
#define __AVR_DEVICE_NAME__ atxmega64a3u

#elif defined(__AVR_ATxmega64B3__)
#define __AVR_DEVICE_NAME__ atxmega64b3

#elif defined(__AVR_ATxmega64C3__)
#define __AVR_DEVICE_NAME__ atxmega64c3

#elif defined(__AVR_ATxmega64D3__)
#define __AVR_DEVICE_NAME__ atxmega64d3

#elif defined(__AVR_ATxmega64A4__)
#define __AVR_DEVICE_NAME__ atxmega64a4

#elif defined(__AVR_ATxmega64A4U__)
#define __AVR_DEVICE_NAME__ atxmega64a4u

#elif defined(__AVR_ATxmega64D4__)
#define __AVR_DEVICE_NAME__ atxmega64d4

#elif defined(__AVR_ATxmega128A1__)
#define __AVR_DEVICE_NAME__ atxmega128a1

#elif defined(__AVR_ATxmega128A1revD__) || defined(__AVR_ATxmega128A1REVD__)
#define __AVR_DEVICE_NAME__ atxmega128a1revd

#elif defined(__AVR_ATxmega128A1U__)
#define __AVR_DEVICE_NAME__ atxmega128a1u

#elif defined(__AVR_ATxmega128B1__)
#define __AVR_DEVICE_NAME__ atxmega128b1

#elif defined(__AVR_ATxmega128A3__)
#define __AVR_DEVICE_NAME__ atxmega128a3

#elif defined(__AVR_ATxmega128A3U__)
#define __AVR_DEVICE_NAME__ atxmega128a3u

#elif defined(__AVR_ATxmega128B3__)
#define __AVR_DEVICE_NAME__ atxmega128b3

#elif defined(__AVR_ATxmega128C3__)
#define __AVR_DEVICE_NAME__ atxmega128c3

#elif defined(__AVR_ATxmega128D3__)
#define __AVR_DEVICE_NAME__ atxmega128d3

#elif defined(__AVR_ATxmega128A4__)
#define __AVR_DEVICE_NAME__ atxmega128a4

#elif defined(__AVR_ATxmega128A4U__)
#define __AVR_DEVICE_NAME__ atxmega128a4u

#elif defined(__AVR_ATxmega128D4__)
#define __AVR_DEVICE_NAME__ atxmega128d4

#elif defined(__AVR_ATxmega192A1__)
#define __AVR_DEVICE_NAME__ atxmega192a1

#elif defined(__AVR_ATxmega192A3__)
#define __AVR_DEVICE_NAME__ atxmega192a3

#elif defined(__AVR_ATxmega192A3U__)
#define __AVR_DEVICE_NAME__ atxmega192a3u

#elif defined(__AVR_ATxmega192C3__)
#define __AVR_DEVICE_NAME__ atxmega192c3

#elif defined(__AVR_ATxmega192D3__)
#define __AVR_DEVICE_NAME__ atxmega192d3

#elif defined(__AVR_ATxmega256A1__)
#define __AVR_DEVICE_NAME__ atxmega256a1

#elif defined(__AVR_ATxmega256A3__)
#define __AVR_DEVICE_NAME__ atxmega256a3

#elif defined(__AVR_ATxmega256A3B__)
#define __AVR_DEVICE_NAME__ atxmega256a3b

#elif defined(__AVR_ATxmega256A3BU__)
#define __AVR_DEVICE_NAME__ atxmega256a3bu

#elif defined(__AVR_ATxmega256A3U__)
#define __AVR_DEVICE_NAME__ atxmega256a3u

#elif defined(__AVR_ATxmega256C3__)
#define __AVR_DEVICE_NAME__ atxmega256c3

#elif defined(__AVR_ATxmega256D3__)
#define __AVR_DEVICE_NAME__ atxmega256d3

#elif defined(__AVR_ATxmega384C3__)
#define __AVR_DEVICE_NAME__ atxmega384c3

#elif defined(__AVR_ATxmega384D3__)
#define __AVR_DEVICE_NAME__ atxmega384d3

#elif defined(__AVR_ATtiny202__)
#define __AVR_DEVICE_NAME__ attiny202

#elif defined(__AVR_ATtiny204__)
#define __AVR_DEVICE_NAME__ attiny204

#elif defined(__AVR_ATtiny212__)
#define __AVR_DEVICE_NAME__ attiny212

#elif defined(__AVR_ATtiny214__)
#define __AVR_DEVICE_NAME__ attiny214

#elif defined(__AVR_ATtiny402__)
#define __AVR_DEVICE_NAME__ attiny402

#elif defined(__AVR_ATtiny404__)
#define __AVR_DEVICE_NAME__ attiny404

#elif defined(__AVR_ATtiny406__)
#define __AVR_DEVICE_NAME__ attiny406

#elif defined(__AVR_ATtiny412__)
#define __AVR_DEVICE_NAME__ attiny412

#elif defined(__AVR_ATtiny414__)
#define __AVR_DEVICE_NAME__ attiny414

#elif defined(__AVR_ATtiny416__)
#define __AVR_DEVICE_NAME__ attiny416

#elif defined(__AVR_ATtiny416auto__)
#define __AVR_DEVICE_NAME__ attiny416auto

#elif defined(__AVR_ATtiny417__)
#define __AVR_DEVICE_NAME__ attiny417

#elif defined(__AVR_ATtiny424__)
#define __AVR_DEVICE_NAME__ attiny424

#elif defined(__AVR_ATtiny426__)
#define __AVR_DEVICE_NAME__ attiny426

#elif defined(__AVR_ATtiny427__)
#define __AVR_DEVICE_NAME__ attiny427

#elif defined(__AVR_ATtiny804__)
#define __AVR_DEVICE_NAME__ attiny804

#elif defined(__AVR_ATtiny806__)
#define __AVR_DEVICE_NAME__ attiny806

#elif defined(__AVR_ATtiny807__)
#define __AVR_DEVICE_NAME__ attiny807

#elif defined(__AVR_ATtiny814__)
#define __AVR_DEVICE_NAME__ attiny814

#elif defined(__AVR_ATtiny816__)
#define __AVR_DEVICE_NAME__ attiny816

#elif defined(__AVR_ATtiny817__)
#define __AVR_DEVICE_NAME__ attiny817

#elif defined(__AVR_ATtiny824__)
#define __AVR_DEVICE_NAME__ attiny824

#elif defined(__AVR_ATtiny826__)
#define __AVR_DEVICE_NAME__ attiny826

#elif defined(__AVR_ATtiny827__)
#define __AVR_DEVICE_NAME__ attiny827

#elif defined(__AVR_ATtiny1604__)
#define __AVR_DEVICE_NAME__ attiny1604

#elif defined(__AVR_ATtiny1606__)
#define __AVR_DEVICE_NAME__ attiny1606

#elif defined(__AVR_ATtiny1607__)
#define __AVR_DEVICE_NAME__ attiny1607

#elif defined(__AVR_ATtiny1614__)
#define __AVR_DEVICE_NAME__ attiny1614

#elif defined(__AVR_ATtiny1616__)
#define __AVR_DEVICE_NAME__ attiny1616

#elif defined(__AVR_ATtiny1617__)
#define __AVR_DEVICE_NAME__ attiny1617

#elif defined(__AVR_ATtiny1624__)
#define __AVR_DEVICE_NAME__ attiny1624

#elif defined(__AVR_ATtiny1626__)
#define __AVR_DEVICE_NAME__ attiny1626

#elif defined(__AVR_ATtiny1627__)
#define __AVR_DEVICE_NAME__ attiny1627

#elif defined(__AVR_ATtiny3214__)
#define __AVR_DEVICE_NAME__ attiny3214

#elif defined(__AVR_ATtiny3216__)
#define __AVR_DEVICE_NAME__ attiny3216

#elif defined(__AVR_ATtiny3217__)
#define __AVR_DEVICE_NAME__ attiny3217

#elif defined(__AVR_ATtiny3224__)
#define __AVR_DEVICE_NAME__ attiny3224

#elif defined(__AVR_ATtiny3226__)
#define __AVR_DEVICE_NAME__ attiny3226

#elif defined(__AVR_ATtiny3227__)
#define __AVR_DEVICE_NAME__ attiny3227

#elif defined(__AVR_ATmega808__)
#define __AVR_DEVICE_NAME__ atmega808

#elif defined(__AVR_ATmega809__)
#define __AVR_DEVICE_NAME__ atmega809

#elif defined(__AVR_ATmega1608__)
#define __AVR_DEVICE_NAME__ atmega1608

#elif defined(__AVR_ATmega1609__)
#define __AVR_DEVICE_NAME__ atmega1609

#elif defined(__AVR_ATmega3208__)
#define __AVR_DEVICE_NAME__ atmega3208

#elif defined(__AVR_ATmega3209__)
#define __AVR_DEVICE_NAME__ atmega3209

#elif defined(__AVR_ATmega4808__)
#define __AVR_DEVICE_NAME__ atmega4808

#elif defined(__AVR_ATmega4809__)
#define __AVR_DEVICE_NAME__ atmega4809

#elif defined(__AVR_AVR8EA28__)
#define __AVR_DEVICE_NAME__ avr8ea28

#elif defined(__AVR_AVR8EA32__)
#define __AVR_DEVICE_NAME__ avr8ea32

#elif defined(__AVR_AVR16DD14__)
#define __AVR_DEVICE_NAME__ avr16dd14

#elif defined(__AVR_AVR16DU14__)
#define __AVR_DEVICE_NAME__ avr16du14

#elif defined(__AVR_AVR16EB14__)
#define __AVR_DEVICE_NAME__ avr16eb14

#elif defined(__AVR_AVR16DD20__)
#define __AVR_DEVICE_NAME__ avr16dd20

#elif defined(__AVR_AVR16DU20__)
#define __AVR_DEVICE_NAME__ avr16du20

#elif defined(__AVR_AVR16EB20__)
#define __AVR_DEVICE_NAME__ avr16eb20

#elif defined(__AVR_AVR16DD28__)
#define __AVR_DEVICE_NAME__ avr16dd28

#elif defined(__AVR_AVR16DU28__)
#define __AVR_DEVICE_NAME__ avr16du28

#elif defined(__AVR_AVR16EA28__)
#define __AVR_DEVICE_NAME__ avr16ea28

#elif defined(__AVR_AVR16EB28__)
#define __AVR_DEVICE_NAME__ avr16eb28

#elif defined(__AVR_AVR16DD32__)
#define __AVR_DEVICE_NAME__ avr16dd32

#elif defined(__AVR_AVR16DU32__)
#define __AVR_DEVICE_NAME__ avr16du32

#elif defined(__AVR_AVR16EA32__)
#define __AVR_DEVICE_NAME__ avr16ea32

#elif defined(__AVR_AVR16EB32__)
#define __AVR_DEVICE_NAME__ avr16eb32

#elif defined(__AVR_AVR16EA48__)
#define __AVR_DEVICE_NAME__ avr16ea48

#elif defined(__AVR_AVR32DD14__)
#define __AVR_DEVICE_NAME__ avr32dd14

#elif defined(__AVR_AVR32DU14__)
#define __AVR_DEVICE_NAME__ avr32du14

#elif defined(__AVR_AVR32DD20__)
#define __AVR_DEVICE_NAME__ avr32dd20

#elif defined(__AVR_AVR32DU20__)
#define __AVR_DEVICE_NAME__ avr32du20

#elif defined(__AVR_AVR32DA28__)
#define __AVR_DEVICE_NAME__ avr32da28

#elif defined(__AVR_AVR32DB28__)
#define __AVR_DEVICE_NAME__ avr32db28

#elif defined(__AVR_AVR32DD28__)
#define __AVR_DEVICE_NAME__ avr32dd28

#elif defined(__AVR_AVR32DU28__)
#define __AVR_DEVICE_NAME__ avr32du28

#elif defined(__AVR_AVR32EA28__)
#define __AVR_DEVICE_NAME__ avr32ea28

#elif defined(__AVR_AVR32DA32__)
#define __AVR_DEVICE_NAME__ avr32da32

#elif defined(__AVR_AVR32DB32__)
#define __AVR_DEVICE_NAME__ avr32db32

#elif defined(__AVR_AVR32DD32__)
#define __AVR_DEVICE_NAME__ avr32dd32

#elif defined(__AVR_AVR32DU32__)
#define __AVR_DEVICE_NAME__ avr32du32

#elif defined(__AVR_AVR32EA32__)
#define __AVR_DEVICE_NAME__ avr32ea32

#elif defined(__AVR_AVR32DA48__)
#define __AVR_DEVICE_NAME__ avr32da48

#elif defined(__AVR_AVR32DB48__)
#define __AVR_DEVICE_NAME__ avr32db48

#elif defined(__AVR_AVR32EA48__)
#define __AVR_DEVICE_NAME__ avr32ea48

#elif defined(__AVR_AVR64DD14__)
#define __AVR_DEVICE_NAME__ avr64dd14

#elif defined(__AVR_AVR64DD20__)
#define __AVR_DEVICE_NAME__ avr64dd20

#elif defined(__AVR_AVR64DA28__)
#define __AVR_DEVICE_NAME__ avr64da28

#elif defined(__AVR_AVR64DB28__)
#define __AVR_DEVICE_NAME__ avr64db28

#elif defined(__AVR_AVR64DD28__)
#define __AVR_DEVICE_NAME__ avr64dd28

#elif defined(__AVR_AVR64DU28__)
#define __AVR_DEVICE_NAME__ avr64du28

#elif defined(__AVR_AVR64EA28__)
#define __AVR_DEVICE_NAME__ avr64ea28

#elif defined(__AVR_AVR64DA32__)
#define __AVR_DEVICE_NAME__ avr64da32

#elif defined(__AVR_AVR64DB32__)
#define __AVR_DEVICE_NAME__ avr64db32

#elif defined(__AVR_AVR64DD32__)
#define __AVR_DEVICE_NAME__ avr64dd32

#elif defined(__AVR_AVR64DU32__)
#define __AVR_DEVICE_NAME__ avr64du32

#elif defined(__AVR_AVR64EA32__)
#define __AVR_DEVICE_NAME__ avr64ea32

#elif defined(__AVR_AVR64DA48__)
#define __AVR_DEVICE_NAME__ avr64da48

#elif defined(__AVR_AVR64DB48__)
#define __AVR_DEVICE_NAME__ avr64db48

#elif defined(__AVR_AVR64EA48__)
#define __AVR_DEVICE_NAME__ avr64ea48

#elif defined(__AVR_AVR64DA64__)
#define __AVR_DEVICE_NAME__ avr64da64

#elif defined(__AVR_AVR64DB64__)
#define __AVR_DEVICE_NAME__ avr64db64

#elif defined(__AVR_AVR128DA28__)
#define __AVR_DEVICE_NAME__ avr128da28

#elif defined(__AVR_AVR128DB28__)
#define __AVR_DEVICE_NAME__ avr128db28

#elif defined(__AVR_AVR128DA32__)
#define __AVR_DEVICE_NAME__ avr128da32

#elif defined(__AVR_AVR128DB32__)
#define __AVR_DEVICE_NAME__ avr128db32

#elif defined(__AVR_AVR128DA48__)
#define __AVR_DEVICE_NAME__ avr128da48

#elif defined(__AVR_AVR128DB48__)
#define __AVR_DEVICE_NAME__ avr128db48

#elif defined(__AVR_AVR128DA64__)
#define __AVR_DEVICE_NAME__ avr128da64

#elif defined(__AVR_AVR128DB64__)
#define __AVR_DEVICE_NAME__ avr128db64

#endif
#endif
